package com.redefine.welikegreendaogenerator;

import org.greenrobot.greendao.generator.DaoGenerator;
import org.greenrobot.greendao.generator.Entity;
import org.greenrobot.greendao.generator.Schema;

public class GreenDaoGenerator {

    public static void main(String[] args) throws Exception {
        DaoGenerator daoGenerator = new DaoGenerator();
        createWeLikeSchema(daoGenerator);
        createIMSchema(daoGenerator);
        createStorageSchema(daoGenerator);
    }

    private static void createWeLikeSchema(DaoGenerator daoGenerator) throws Exception {
        Schema schema = new Schema(12, "com.redefine.welike.base.dao.welike");

        Entity profile = schema.addEntity("Profile");
        profile.addStringProperty("uid").notNull().unique().primaryKey();
        profile.addStringProperty("nick");
        profile.addStringProperty("head");
        profile.addStringProperty("atoken").notNull();
        profile.addStringProperty("ttype").notNull();
        profile.addStringProperty("rtoken").notNull();
        profile.addStringProperty("expired").notNull();
        profile.addStringProperty("introduction");
        profile.addByteProperty("sex");
        profile.addIntProperty("postsCount");
        profile.addIntProperty("followingCount");
        profile.addIntProperty("followerCount");
        profile.addLongProperty("likedMyPostsCount");
        profile.addLongProperty("myLikedPostsCount");
        profile.addIntProperty("completeLevel").notNull();
        profile.addBooleanProperty("login").notNull();
        profile.addIntProperty("vip");
        profile.addStringProperty("intrests");
        profile.addIntProperty("status");
//        Entity homePost = schema.addEntity("HomePost");
//        homePost.addStringProperty("pid").notNull().unique().primaryKey();
//        homePost.addStringProperty("uid").notNull();
//        homePost.addStringProperty("nick").notNull();
//        homePost.addStringProperty("head");
//        homePost.addLongProperty("time").notNull();
//        homePost.addLongProperty("insertTime").notNull();
//        homePost.addStringProperty("from");
//        homePost.addByteProperty("type").notNull();
//        homePost.addLongProperty("likeCount").notNull();
//        homePost.addIntProperty("likeValue").notNull();
//        homePost.addIntProperty("commentCount").notNull();
//        homePost.addIntProperty("forwardCount").notNull();
//        homePost.addStringProperty("text").notNull();
//        homePost.addStringProperty("summary").notNull();
//        homePost.addStringProperty("rich");
//        homePost.addStringProperty("placeid");
//        homePost.addStringProperty("place");
//        homePost.addStringProperty("pic1");
//        homePost.addStringProperty("pic1Large");
//        homePost.addStringProperty("pic2");
//        homePost.addStringProperty("pic2Large");
//        homePost.addStringProperty("pic3");
//        homePost.addStringProperty("pic3Large");
//        homePost.addStringProperty("pic4");
//        homePost.addStringProperty("pic4Large");
//        homePost.addStringProperty("pic5");
//        homePost.addStringProperty("pic5Large");
//        homePost.addStringProperty("pic6");
//        homePost.addStringProperty("pic6Large");
//        homePost.addStringProperty("pic7");
//        homePost.addStringProperty("pic7Large");
//        homePost.addStringProperty("pic8");
//        homePost.addStringProperty("pic8Large");
//        homePost.addStringProperty("pic9");
//        homePost.addStringProperty("pic9Large");
//        homePost.addStringProperty("video");
//        homePost.addStringProperty("videoThumb");
//        homePost.addStringProperty("link");
//        homePost.addStringProperty("linkTitle");
//        homePost.addStringProperty("linkText");
//        homePost.addStringProperty("linkImg");
//        homePost.addStringProperty("forwardPid");
//        homePost.addBooleanProperty("forwardDeleted");
//        homePost.addStringProperty("forwardUid");
//        homePost.addStringProperty("forwardNick");
//        homePost.addStringProperty("forwardHead");
//        homePost.addByteProperty("forwardType");
//        homePost.addLongProperty("forwardLikeCount");
//        homePost.addIntProperty("forwardLikeValue");
//        homePost.addIntProperty("forwardCommentCount");
//        homePost.addIntProperty("forwardForwardCount");
//        homePost.addStringProperty("forwardText");
//        homePost.addStringProperty("forwardSummary");
//        homePost.addStringProperty("forwardRich");
//        homePost.addStringProperty("forwardPic1");
//        homePost.addStringProperty("forwardPic2");
//        homePost.addStringProperty("forwardPic3");
//        homePost.addStringProperty("forwardPic4");
//        homePost.addStringProperty("forwardPic5");
//        homePost.addStringProperty("forwardPic6");
//        homePost.addStringProperty("forwardPic7");
//        homePost.addStringProperty("forwardPic8");
//        homePost.addStringProperty("forwardPic9");
//        homePost.addStringProperty("forwardPic1Large");
//        homePost.addStringProperty("forwardPic2Large");
//        homePost.addStringProperty("forwardPic3Large");
//        homePost.addStringProperty("forwardPic4Large");
//        homePost.addStringProperty("forwardPic5Large");
//        homePost.addStringProperty("forwardPic6Large");
//        homePost.addStringProperty("forwardPic7Large");
//        homePost.addStringProperty("forwardPic8Large");
//        homePost.addStringProperty("forwardPic9Large");
//        homePost.addStringProperty("forwardVideo");
//        homePost.addStringProperty("forwardVideoThumb");
//        homePost.addStringProperty("forwardLink");
//        homePost.addStringProperty("forwardLinkTitle");
//        homePost.addStringProperty("forwardLinkText");
//        homePost.addStringProperty("forwardLinkImg");
//
//        Entity hotPost = schema.addEntity("HotPost");
//        hotPost.addStringProperty("pid").notNull().unique().primaryKey();
//        hotPost.addStringProperty("uid").notNull();
//        hotPost.addStringProperty("nick").notNull();
//        hotPost.addStringProperty("head");
//        hotPost.addLongProperty("time").notNull();
//        hotPost.addLongProperty("insertTime").notNull();
//        hotPost.addStringProperty("from");
//        hotPost.addByteProperty("type").notNull();
//        hotPost.addLongProperty("likeCount").notNull();
//        hotPost.addIntProperty("likeValue").notNull();
//        hotPost.addIntProperty("commentCount").notNull();
//        hotPost.addIntProperty("forwardCount").notNull();
//        hotPost.addStringProperty("text").notNull();
//        hotPost.addStringProperty("summary").notNull();
//        hotPost.addStringProperty("rich");
//        hotPost.addStringProperty("placeid");
//        hotPost.addStringProperty("place");
//        hotPost.addStringProperty("pic1");
//        hotPost.addStringProperty("pic1Large");
//        hotPost.addStringProperty("pic2");
//        hotPost.addStringProperty("pic2Large");
//        hotPost.addStringProperty("pic3");
//        hotPost.addStringProperty("pic3Large");
//        hotPost.addStringProperty("pic4");
//        hotPost.addStringProperty("pic4Large");
//        hotPost.addStringProperty("pic5");
//        hotPost.addStringProperty("pic5Large");
//        hotPost.addStringProperty("pic6");
//        hotPost.addStringProperty("pic6Large");
//        hotPost.addStringProperty("pic7");
//        hotPost.addStringProperty("pic7Large");
//        hotPost.addStringProperty("pic8");
//        hotPost.addStringProperty("pic8Large");
//        hotPost.addStringProperty("pic9");
//        hotPost.addStringProperty("pic9Large");
//        hotPost.addStringProperty("video");
//        hotPost.addStringProperty("videoThumb");
//        hotPost.addStringProperty("link");
//        hotPost.addStringProperty("linkTitle");
//        hotPost.addStringProperty("linkText");
//        hotPost.addStringProperty("linkImg");
//        hotPost.addStringProperty("forwardPid");
//        hotPost.addBooleanProperty("forwardDeleted");
//        hotPost.addStringProperty("forwardUid");
//        hotPost.addStringProperty("forwardNick");
//        hotPost.addStringProperty("forwardHead");
//        hotPost.addByteProperty("forwardType");
//        hotPost.addLongProperty("forwardLikeCount");
//        hotPost.addIntProperty("forwardLikeValue");
//        hotPost.addIntProperty("forwardCommentCount");
//        hotPost.addIntProperty("forwardForwardCount");
//        hotPost.addStringProperty("forwardText");
//        hotPost.addStringProperty("forwardSummary");
//        hotPost.addStringProperty("forwardRich");
//        hotPost.addStringProperty("forwardPic1");
//        hotPost.addStringProperty("forwardPic2");
//        hotPost.addStringProperty("forwardPic3");
//        hotPost.addStringProperty("forwardPic4");
//        hotPost.addStringProperty("forwardPic5");
//        hotPost.addStringProperty("forwardPic6");
//        hotPost.addStringProperty("forwardPic7");
//        hotPost.addStringProperty("forwardPic8");
//        hotPost.addStringProperty("forwardPic9");
//        hotPost.addStringProperty("forwardPic1Large");
//        hotPost.addStringProperty("forwardPic2Large");
//        hotPost.addStringProperty("forwardPic3Large");
//        hotPost.addStringProperty("forwardPic4Large");
//        hotPost.addStringProperty("forwardPic5Large");
//        hotPost.addStringProperty("forwardPic6Large");
//        hotPost.addStringProperty("forwardPic7Large");
//        hotPost.addStringProperty("forwardPic8Large");
//        hotPost.addStringProperty("forwardPic9Large");
//        hotPost.addStringProperty("forwardVideo");
//        hotPost.addStringProperty("forwardVideoThumb");
//        hotPost.addStringProperty("forwardLink");
//        hotPost.addStringProperty("forwardLinkTitle");
//        hotPost.addStringProperty("forwardLinkText");
//        hotPost.addStringProperty("forwardLinkImg");

        Entity searchHistory = schema.addEntity("SearchHistory");
        searchHistory.addIdProperty().autoincrement();
        searchHistory.addStringProperty("keyword").unique().notNull();
        searchHistory.addLongProperty("time").notNull();

        Entity topicSearchHistory = schema.addEntity("TopicSearchHistory");
        topicSearchHistory.addIdProperty().autoincrement();
        topicSearchHistory.addStringProperty("keyword").unique().notNull();
        topicSearchHistory.addLongProperty("time").notNull();

        Entity user = schema.addEntity("User");
        user.addStringProperty("uid").unique().primaryKey();
        user.addStringProperty("nick").notNull();
        user.addByteProperty("sex").notNull();
        user.addLongProperty("created").notNull();
        user.addStringProperty("head");
        user.addLongProperty("atTime");
        user.addIntProperty("vip");

        Entity draft = schema.addEntity("Draft");
        draft.addStringProperty("draftId").notNull().unique().primaryKey();
        draft.addLongProperty("time").notNull();
        draft.addByteProperty("type").notNull();
        draft.addBooleanProperty("show").notNull();
        draft.addStringProperty("commentPid");
        draft.addStringProperty("replyCid");
        draft.addStringProperty("replyReplyId");
        draft.addStringProperty("text");
        draft.addStringProperty("summary");
        draft.addStringProperty("rich");
        draft.addStringProperty("commentUid");
        draft.addStringProperty("commentNick");
        draft.addStringProperty("fText");
        draft.addStringProperty("fSummary");
        draft.addStringProperty("fRich");
        draft.addStringProperty("cText");
        draft.addStringProperty("cSummary");
        draft.addStringProperty("cRich");
        draft.addStringProperty("rText");
        draft.addStringProperty("rSummary");
        draft.addStringProperty("rRich");
        draft.addStringProperty("placeid");
        draft.addStringProperty("place");
        draft.addStringProperty("latitude");
        draft.addStringProperty("longitude");
        draft.addBooleanProperty("asComment").notNull();
        draft.addBooleanProperty("asRepost").notNull();
        draft.addStringProperty("pic1");
        draft.addStringProperty("pic1Tmp");
        draft.addIntProperty("pic1Width");
        draft.addIntProperty("pic1Height");
        draft.addStringProperty("pic1Mimetype");
        draft.addStringProperty("pic1Key");
        draft.addStringProperty("pic1Url");
        draft.addStringProperty("pic2");
        draft.addStringProperty("pic2Tmp");
        draft.addIntProperty("pic2Width");
        draft.addIntProperty("pic2Height");
        draft.addStringProperty("pic2Mimetype");
        draft.addStringProperty("pic2Key");
        draft.addStringProperty("pic2Url");
        draft.addStringProperty("pic3");
        draft.addStringProperty("pic3Tmp");
        draft.addIntProperty("pic3Width");
        draft.addIntProperty("pic3Height");
        draft.addStringProperty("pic3Mimetype");
        draft.addStringProperty("pic3Key");
        draft.addStringProperty("pic3Url");
        draft.addStringProperty("pic4");
        draft.addStringProperty("pic4Tmp");
        draft.addIntProperty("pic4Width");
        draft.addIntProperty("pic4Height");
        draft.addStringProperty("pic4Mimetype");
        draft.addStringProperty("pic4Key");
        draft.addStringProperty("pic4Url");
        draft.addStringProperty("pic5");
        draft.addStringProperty("pic5Tmp");
        draft.addIntProperty("pic5Width");
        draft.addIntProperty("pic5Height");
        draft.addStringProperty("pic5Mimetype");
        draft.addStringProperty("pic5Key");
        draft.addStringProperty("pic5Url");
        draft.addStringProperty("pic6");
        draft.addStringProperty("pic6Tmp");
        draft.addIntProperty("pic6Width");
        draft.addIntProperty("pic6Height");
        draft.addStringProperty("pic6Mimetype");
        draft.addStringProperty("pic6Key");
        draft.addStringProperty("pic6Url");
        draft.addStringProperty("pic7");
        draft.addStringProperty("pic7Tmp");
        draft.addIntProperty("pic7Width");
        draft.addIntProperty("pic7Height");
        draft.addStringProperty("pic7Mimetype");
        draft.addStringProperty("pic7Key");
        draft.addStringProperty("pic7Url");
        draft.addStringProperty("pic8");
        draft.addStringProperty("pic8Tmp");
        draft.addIntProperty("pic8Width");
        draft.addIntProperty("pic8Height");
        draft.addStringProperty("pic8Mimetype");
        draft.addStringProperty("pic8Key");
        draft.addStringProperty("pic8Url");
        draft.addStringProperty("pic9");
        draft.addStringProperty("pic9Tmp");
        draft.addIntProperty("pic9Width");
        draft.addIntProperty("pic9Height");
        draft.addStringProperty("pic9Mimetype");
        draft.addStringProperty("pic9Key");
        draft.addStringProperty("pic9Url");
        draft.addStringProperty("video");
        draft.addStringProperty("videoTmp");
        draft.addStringProperty("videoMimetype");
        draft.addLongProperty("videoDur");
        draft.addStringProperty("videoKey");
        draft.addStringProperty("videoUrl");
        draft.addStringProperty("videoThumb");
        draft.addStringProperty("videoThumbTmp");
        draft.addStringProperty("videoThumbKey");
        draft.addStringProperty("videoThumbUrl");
        draft.addIntProperty("videoWidth");
        draft.addIntProperty("videoHeight");
        draft.addStringProperty("forwardPid");
        draft.addBooleanProperty("forwardDeleted");
        draft.addStringProperty("forwardUid");
        draft.addStringProperty("forwardNick");
        draft.addStringProperty("forwardHead");
        draft.addByteProperty("forwardType");
        draft.addLongProperty("forwardLikeCount");
        draft.addIntProperty("forwardLikeValue");
        draft.addIntProperty("forwardCommentCount");
        draft.addIntProperty("forwardForwardCount");
        draft.addStringProperty("forwardText");
        draft.addStringProperty("forwardSummary");
        draft.addStringProperty("forwardRich");
        draft.addStringProperty("forwardPic1");
        draft.addStringProperty("forwardPic2");
        draft.addStringProperty("forwardPic3");
        draft.addStringProperty("forwardPic4");
        draft.addStringProperty("forwardPic5");
        draft.addStringProperty("forwardPic6");
        draft.addStringProperty("forwardPic7");
        draft.addStringProperty("forwardPic8");
        draft.addStringProperty("forwardPic9");
        draft.addStringProperty("forwardPic1Large");
        draft.addStringProperty("forwardPic2Large");
        draft.addStringProperty("forwardPic3Large");
        draft.addStringProperty("forwardPic4Large");
        draft.addStringProperty("forwardPic5Large");
        draft.addStringProperty("forwardPic6Large");
        draft.addStringProperty("forwardPic7Large");
        draft.addStringProperty("forwardPic8Large");
        draft.addStringProperty("forwardPic9Large");
        draft.addStringProperty("forwardVideo");
        draft.addStringProperty("forwardVideoThumb");
        draft.addStringProperty("forwardLink");
        draft.addStringProperty("forwardLinkTitle");
        draft.addStringProperty("forwardLinkText");
        draft.addStringProperty("forwardLinkImg");

        daoGenerator.generateAll(schema, "../base/src/main/java");
    }

    private static void createIMSchema(DaoGenerator daoGenerator) throws Exception {
//        Schema schema = new Schema(5, "com.redefine.welike.base.dao.im");
//
//        Entity message = schema.addEntity("Message");
//        message.addStringProperty("mid").unique().primaryKey();
//        message.addStringProperty("sid").notNull();
//        message.addStringProperty("sessionNick").notNull();
//        message.addStringProperty("sessionHead");
//        message.addStringProperty("senderUid").notNull();
//        message.addStringProperty("senderNick").notNull();
//        message.addStringProperty("senderHead");
//        message.addByteProperty("sessionType").notNull();
//        message.addByteProperty("status").notNull();
//        message.addLongProperty("time").notNull();
//        message.addByteProperty("type").notNull();
//        message.addStringProperty("text");
//        message.addStringProperty("thumb");
//        message.addStringProperty("pic");
//        message.addStringProperty("audio");
//        message.addStringProperty("video");
//        message.addStringProperty("fileName");
//
//        Entity session = schema.addEntity("Session");
//        session.addStringProperty("sid").unique().primaryKey();
//        session.addStringProperty("sessionNick").notNull();
//        session.addStringProperty("sessionHead");
//        session.addStringProperty("singleUid");
//        session.addByteProperty("msgType");
//        session.addBooleanProperty("enableChat");
//        session.addBooleanProperty("visableChat");
//        session.addBooleanProperty("isGreet");
//        session.addByteProperty("sessionType").notNull();
//        session.addLongProperty("time").notNull();
//        session.addIntProperty("unreadCount").notNull();
//        session.addStringProperty("content");
//
//        Entity accountSetting = schema.addEntity("AccountSetting");
//        accountSetting.addStringProperty("uid").unique().primaryKey();
//        accountSetting.addStringProperty("imMessageCursor");
//        accountSetting.addIntProperty("mentionMsgUnReadCount");
//        accountSetting.addIntProperty("commentMsgUnReadCount");
//        accountSetting.addIntProperty("likeMsgUnReadCount");
//
//        daoGenerator.generateAll(schema, "../base/src/main/java");
    }

    private static void createStorageSchema(DaoGenerator daoGenerator) throws Exception {
        Schema schema = new Schema(3, "com.redefine.welike.base.dao.storage");

        Entity upload = schema.addEntity("Upload");
        upload.addStringProperty("sign").unique().primaryKey();
        upload.addStringProperty("uploadid").notNull();

        Entity upgraded = schema.addEntity("Upgraded");
        upgraded.addStringProperty("updateId").unique().primaryKey();
        upgraded.addStringProperty("os").notNull();
        upgraded.addStringProperty("updateContent").notNull();
        upgraded.addStringProperty("version").notNull();
        upgraded.addStringProperty("updateTitle").notNull();
        upgraded.addStringProperty("url").notNull();
        upgraded.addIntProperty("updateType").notNull();

        daoGenerator.generateAll(schema, "../base/src/main/java");

    }

}
