package com.redefine.welike.base.dao.storage;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.redefine.welike.base.dao.storage.Upload;
import com.redefine.welike.base.dao.storage.Upgraded;

import com.redefine.welike.base.dao.storage.UploadDao;
import com.redefine.welike.base.dao.storage.UpgradedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uploadDaoConfig;
    private final DaoConfig upgradedDaoConfig;

    private final UploadDao uploadDao;
    private final UpgradedDao upgradedDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uploadDaoConfig = daoConfigMap.get(UploadDao.class).clone();
        uploadDaoConfig.initIdentityScope(type);

        upgradedDaoConfig = daoConfigMap.get(UpgradedDao.class).clone();
        upgradedDaoConfig.initIdentityScope(type);

        uploadDao = new UploadDao(uploadDaoConfig, this);
        upgradedDao = new UpgradedDao(upgradedDaoConfig, this);

        registerDao(Upload.class, uploadDao);
        registerDao(Upgraded.class, upgradedDao);
    }
    
    public void clear() {
        uploadDaoConfig.clearIdentityScope();
        upgradedDaoConfig.clearIdentityScope();
    }

    public UploadDao getUploadDao() {
        return uploadDao;
    }

    public UpgradedDao getUpgradedDao() {
        return upgradedDao;
    }

}
