package com.redefine.welike.base.dao.storage;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "UPGRADED".
 */
@Entity
public class Upgraded {

    @Id
    @Unique
    private String updateId;

    @NotNull
    private String os;

    @NotNull
    private String updateContent;

    @NotNull
    private String version;

    @NotNull
    private String updateTitle;

    @NotNull
    private String url;
    private int updateType;

    @Generated
    public Upgraded() {
    }

    public Upgraded(String updateId) {
        this.updateId = updateId;
    }

    @Generated
    public Upgraded(String updateId, String os, String updateContent, String version, String updateTitle, String url, int updateType) {
        this.updateId = updateId;
        this.os = os;
        this.updateContent = updateContent;
        this.version = version;
        this.updateTitle = updateTitle;
        this.url = url;
        this.updateType = updateType;
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    @NotNull
    public String getOs() {
        return os;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOs(@NotNull String os) {
        this.os = os;
    }

    @NotNull
    public String getUpdateContent() {
        return updateContent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdateContent(@NotNull String updateContent) {
        this.updateContent = updateContent;
    }

    @NotNull
    public String getVersion() {
        return version;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVersion(@NotNull String version) {
        this.version = version;
    }

    @NotNull
    public String getUpdateTitle() {
        return updateTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdateTitle(@NotNull String updateTitle) {
        this.updateTitle = updateTitle;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    public int getUpdateType() {
        return updateType;
    }

    public void setUpdateType(int updateType) {
        this.updateType = updateType;
    }

}
