package com.redefine.welike.base.dao.storage;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "UPLOAD".
 */
@Entity
public class Upload {

    @Id
    @Unique
    private String sign;

    @NotNull
    private String uploadid;

    @Generated
    public Upload() {
    }

    public Upload(String sign) {
        this.sign = sign;
    }

    @Generated
    public Upload(String sign, String uploadid) {
        this.sign = sign;
        this.uploadid = uploadid;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    @NotNull
    public String getUploadid() {
        return uploadid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUploadid(@NotNull String uploadid) {
        this.uploadid = uploadid;
    }

}
