package com.redefine.welike.base.dao.welike;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "DRAFT".
 */
public class DraftDao extends AbstractDao<Draft, String> {

    public static final String TABLENAME = "DRAFT";

    /**
     * Properties of entity Draft.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DraftId = new Property(0, String.class, "draftId", true, "DRAFT_ID");
        public final static Property Time = new Property(1, long.class, "time", false, "TIME");
        public final static Property Type = new Property(2, byte.class, "type", false, "TYPE");
        public final static Property Show = new Property(3, boolean.class, "show", false, "SHOW");
        public final static Property CommentPid = new Property(4, String.class, "commentPid", false, "COMMENT_PID");
        public final static Property ReplyCid = new Property(5, String.class, "replyCid", false, "REPLY_CID");
        public final static Property ReplyReplyId = new Property(6, String.class, "replyReplyId", false, "REPLY_REPLY_ID");
        public final static Property Text = new Property(7, String.class, "text", false, "TEXT");
        public final static Property Summary = new Property(8, String.class, "summary", false, "SUMMARY");
        public final static Property Rich = new Property(9, String.class, "rich", false, "RICH");
        public final static Property CommentUid = new Property(10, String.class, "commentUid", false, "COMMENT_UID");
        public final static Property CommentNick = new Property(11, String.class, "commentNick", false, "COMMENT_NICK");
        public final static Property FText = new Property(12, String.class, "fText", false, "F_TEXT");
        public final static Property FSummary = new Property(13, String.class, "fSummary", false, "F_SUMMARY");
        public final static Property FRich = new Property(14, String.class, "fRich", false, "F_RICH");
        public final static Property CText = new Property(15, String.class, "cText", false, "C_TEXT");
        public final static Property CSummary = new Property(16, String.class, "cSummary", false, "C_SUMMARY");
        public final static Property CRich = new Property(17, String.class, "cRich", false, "C_RICH");
        public final static Property RText = new Property(18, String.class, "rText", false, "R_TEXT");
        public final static Property RSummary = new Property(19, String.class, "rSummary", false, "R_SUMMARY");
        public final static Property RRich = new Property(20, String.class, "rRich", false, "R_RICH");
        public final static Property Placeid = new Property(21, String.class, "placeid", false, "PLACEID");
        public final static Property Place = new Property(22, String.class, "place", false, "PLACE");
        public final static Property Latitude = new Property(23, String.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(24, String.class, "longitude", false, "LONGITUDE");
        public final static Property AsComment = new Property(25, boolean.class, "asComment", false, "AS_COMMENT");
        public final static Property AsRepost = new Property(26, boolean.class, "asRepost", false, "AS_REPOST");
        public final static Property Pic1 = new Property(27, String.class, "pic1", false, "PIC1");
        public final static Property Pic1Tmp = new Property(28, String.class, "pic1Tmp", false, "PIC1_TMP");
        public final static Property Pic1Width = new Property(29, Integer.class, "pic1Width", false, "PIC1_WIDTH");
        public final static Property Pic1Height = new Property(30, Integer.class, "pic1Height", false, "PIC1_HEIGHT");
        public final static Property Pic1Mimetype = new Property(31, String.class, "pic1Mimetype", false, "PIC1_MIMETYPE");
        public final static Property Pic1Key = new Property(32, String.class, "pic1Key", false, "PIC1_KEY");
        public final static Property Pic1Url = new Property(33, String.class, "pic1Url", false, "PIC1_URL");
        public final static Property Pic2 = new Property(34, String.class, "pic2", false, "PIC2");
        public final static Property Pic2Tmp = new Property(35, String.class, "pic2Tmp", false, "PIC2_TMP");
        public final static Property Pic2Width = new Property(36, Integer.class, "pic2Width", false, "PIC2_WIDTH");
        public final static Property Pic2Height = new Property(37, Integer.class, "pic2Height", false, "PIC2_HEIGHT");
        public final static Property Pic2Mimetype = new Property(38, String.class, "pic2Mimetype", false, "PIC2_MIMETYPE");
        public final static Property Pic2Key = new Property(39, String.class, "pic2Key", false, "PIC2_KEY");
        public final static Property Pic2Url = new Property(40, String.class, "pic2Url", false, "PIC2_URL");
        public final static Property Pic3 = new Property(41, String.class, "pic3", false, "PIC3");
        public final static Property Pic3Tmp = new Property(42, String.class, "pic3Tmp", false, "PIC3_TMP");
        public final static Property Pic3Width = new Property(43, Integer.class, "pic3Width", false, "PIC3_WIDTH");
        public final static Property Pic3Height = new Property(44, Integer.class, "pic3Height", false, "PIC3_HEIGHT");
        public final static Property Pic3Mimetype = new Property(45, String.class, "pic3Mimetype", false, "PIC3_MIMETYPE");
        public final static Property Pic3Key = new Property(46, String.class, "pic3Key", false, "PIC3_KEY");
        public final static Property Pic3Url = new Property(47, String.class, "pic3Url", false, "PIC3_URL");
        public final static Property Pic4 = new Property(48, String.class, "pic4", false, "PIC4");
        public final static Property Pic4Tmp = new Property(49, String.class, "pic4Tmp", false, "PIC4_TMP");
        public final static Property Pic4Width = new Property(50, Integer.class, "pic4Width", false, "PIC4_WIDTH");
        public final static Property Pic4Height = new Property(51, Integer.class, "pic4Height", false, "PIC4_HEIGHT");
        public final static Property Pic4Mimetype = new Property(52, String.class, "pic4Mimetype", false, "PIC4_MIMETYPE");
        public final static Property Pic4Key = new Property(53, String.class, "pic4Key", false, "PIC4_KEY");
        public final static Property Pic4Url = new Property(54, String.class, "pic4Url", false, "PIC4_URL");
        public final static Property Pic5 = new Property(55, String.class, "pic5", false, "PIC5");
        public final static Property Pic5Tmp = new Property(56, String.class, "pic5Tmp", false, "PIC5_TMP");
        public final static Property Pic5Width = new Property(57, Integer.class, "pic5Width", false, "PIC5_WIDTH");
        public final static Property Pic5Height = new Property(58, Integer.class, "pic5Height", false, "PIC5_HEIGHT");
        public final static Property Pic5Mimetype = new Property(59, String.class, "pic5Mimetype", false, "PIC5_MIMETYPE");
        public final static Property Pic5Key = new Property(60, String.class, "pic5Key", false, "PIC5_KEY");
        public final static Property Pic5Url = new Property(61, String.class, "pic5Url", false, "PIC5_URL");
        public final static Property Pic6 = new Property(62, String.class, "pic6", false, "PIC6");
        public final static Property Pic6Tmp = new Property(63, String.class, "pic6Tmp", false, "PIC6_TMP");
        public final static Property Pic6Width = new Property(64, Integer.class, "pic6Width", false, "PIC6_WIDTH");
        public final static Property Pic6Height = new Property(65, Integer.class, "pic6Height", false, "PIC6_HEIGHT");
        public final static Property Pic6Mimetype = new Property(66, String.class, "pic6Mimetype", false, "PIC6_MIMETYPE");
        public final static Property Pic6Key = new Property(67, String.class, "pic6Key", false, "PIC6_KEY");
        public final static Property Pic6Url = new Property(68, String.class, "pic6Url", false, "PIC6_URL");
        public final static Property Pic7 = new Property(69, String.class, "pic7", false, "PIC7");
        public final static Property Pic7Tmp = new Property(70, String.class, "pic7Tmp", false, "PIC7_TMP");
        public final static Property Pic7Width = new Property(71, Integer.class, "pic7Width", false, "PIC7_WIDTH");
        public final static Property Pic7Height = new Property(72, Integer.class, "pic7Height", false, "PIC7_HEIGHT");
        public final static Property Pic7Mimetype = new Property(73, String.class, "pic7Mimetype", false, "PIC7_MIMETYPE");
        public final static Property Pic7Key = new Property(74, String.class, "pic7Key", false, "PIC7_KEY");
        public final static Property Pic7Url = new Property(75, String.class, "pic7Url", false, "PIC7_URL");
        public final static Property Pic8 = new Property(76, String.class, "pic8", false, "PIC8");
        public final static Property Pic8Tmp = new Property(77, String.class, "pic8Tmp", false, "PIC8_TMP");
        public final static Property Pic8Width = new Property(78, Integer.class, "pic8Width", false, "PIC8_WIDTH");
        public final static Property Pic8Height = new Property(79, Integer.class, "pic8Height", false, "PIC8_HEIGHT");
        public final static Property Pic8Mimetype = new Property(80, String.class, "pic8Mimetype", false, "PIC8_MIMETYPE");
        public final static Property Pic8Key = new Property(81, String.class, "pic8Key", false, "PIC8_KEY");
        public final static Property Pic8Url = new Property(82, String.class, "pic8Url", false, "PIC8_URL");
        public final static Property Pic9 = new Property(83, String.class, "pic9", false, "PIC9");
        public final static Property Pic9Tmp = new Property(84, String.class, "pic9Tmp", false, "PIC9_TMP");
        public final static Property Pic9Width = new Property(85, Integer.class, "pic9Width", false, "PIC9_WIDTH");
        public final static Property Pic9Height = new Property(86, Integer.class, "pic9Height", false, "PIC9_HEIGHT");
        public final static Property Pic9Mimetype = new Property(87, String.class, "pic9Mimetype", false, "PIC9_MIMETYPE");
        public final static Property Pic9Key = new Property(88, String.class, "pic9Key", false, "PIC9_KEY");
        public final static Property Pic9Url = new Property(89, String.class, "pic9Url", false, "PIC9_URL");
        public final static Property Video = new Property(90, String.class, "video", false, "VIDEO");
        public final static Property VideoTmp = new Property(91, String.class, "videoTmp", false, "VIDEO_TMP");
        public final static Property VideoMimetype = new Property(92, String.class, "videoMimetype", false, "VIDEO_MIMETYPE");
        public final static Property VideoDur = new Property(93, Long.class, "videoDur", false, "VIDEO_DUR");
        public final static Property VideoKey = new Property(94, String.class, "videoKey", false, "VIDEO_KEY");
        public final static Property VideoUrl = new Property(95, String.class, "videoUrl", false, "VIDEO_URL");
        public final static Property VideoThumb = new Property(96, String.class, "videoThumb", false, "VIDEO_THUMB");
        public final static Property VideoThumbTmp = new Property(97, String.class, "videoThumbTmp", false, "VIDEO_THUMB_TMP");
        public final static Property VideoThumbKey = new Property(98, String.class, "videoThumbKey", false, "VIDEO_THUMB_KEY");
        public final static Property VideoThumbUrl = new Property(99, String.class, "videoThumbUrl", false, "VIDEO_THUMB_URL");
        public final static Property VideoWidth = new Property(100, Integer.class, "videoWidth", false, "VIDEO_WIDTH");
        public final static Property VideoHeight = new Property(101, Integer.class, "videoHeight", false, "VIDEO_HEIGHT");
        public final static Property ForwardPid = new Property(102, String.class, "forwardPid", false, "FORWARD_PID");
        public final static Property ForwardDeleted = new Property(103, Boolean.class, "forwardDeleted", false, "FORWARD_DELETED");
        public final static Property ForwardUid = new Property(104, String.class, "forwardUid", false, "FORWARD_UID");
        public final static Property ForwardNick = new Property(105, String.class, "forwardNick", false, "FORWARD_NICK");
        public final static Property ForwardHead = new Property(106, String.class, "forwardHead", false, "FORWARD_HEAD");
        public final static Property ForwardType = new Property(107, Byte.class, "forwardType", false, "FORWARD_TYPE");
        public final static Property ForwardLikeCount = new Property(108, Long.class, "forwardLikeCount", false, "FORWARD_LIKE_COUNT");
        public final static Property ForwardLikeValue = new Property(109, Integer.class, "forwardLikeValue", false, "FORWARD_LIKE_VALUE");
        public final static Property ForwardCommentCount = new Property(110, Integer.class, "forwardCommentCount", false, "FORWARD_COMMENT_COUNT");
        public final static Property ForwardForwardCount = new Property(111, Integer.class, "forwardForwardCount", false, "FORWARD_FORWARD_COUNT");
        public final static Property ForwardText = new Property(112, String.class, "forwardText", false, "FORWARD_TEXT");
        public final static Property ForwardSummary = new Property(113, String.class, "forwardSummary", false, "FORWARD_SUMMARY");
        public final static Property ForwardRich = new Property(114, String.class, "forwardRich", false, "FORWARD_RICH");
        public final static Property ForwardPic1 = new Property(115, String.class, "forwardPic1", false, "FORWARD_PIC1");
        public final static Property ForwardPic2 = new Property(116, String.class, "forwardPic2", false, "FORWARD_PIC2");
        public final static Property ForwardPic3 = new Property(117, String.class, "forwardPic3", false, "FORWARD_PIC3");
        public final static Property ForwardPic4 = new Property(118, String.class, "forwardPic4", false, "FORWARD_PIC4");
        public final static Property ForwardPic5 = new Property(119, String.class, "forwardPic5", false, "FORWARD_PIC5");
        public final static Property ForwardPic6 = new Property(120, String.class, "forwardPic6", false, "FORWARD_PIC6");
        public final static Property ForwardPic7 = new Property(121, String.class, "forwardPic7", false, "FORWARD_PIC7");
        public final static Property ForwardPic8 = new Property(122, String.class, "forwardPic8", false, "FORWARD_PIC8");
        public final static Property ForwardPic9 = new Property(123, String.class, "forwardPic9", false, "FORWARD_PIC9");
        public final static Property ForwardPic1Large = new Property(124, String.class, "forwardPic1Large", false, "FORWARD_PIC1_LARGE");
        public final static Property ForwardPic2Large = new Property(125, String.class, "forwardPic2Large", false, "FORWARD_PIC2_LARGE");
        public final static Property ForwardPic3Large = new Property(126, String.class, "forwardPic3Large", false, "FORWARD_PIC3_LARGE");
        public final static Property ForwardPic4Large = new Property(127, String.class, "forwardPic4Large", false, "FORWARD_PIC4_LARGE");
        public final static Property ForwardPic5Large = new Property(128, String.class, "forwardPic5Large", false, "FORWARD_PIC5_LARGE");
        public final static Property ForwardPic6Large = new Property(129, String.class, "forwardPic6Large", false, "FORWARD_PIC6_LARGE");
        public final static Property ForwardPic7Large = new Property(130, String.class, "forwardPic7Large", false, "FORWARD_PIC7_LARGE");
        public final static Property ForwardPic8Large = new Property(131, String.class, "forwardPic8Large", false, "FORWARD_PIC8_LARGE");
        public final static Property ForwardPic9Large = new Property(132, String.class, "forwardPic9Large", false, "FORWARD_PIC9_LARGE");
        public final static Property ForwardVideo = new Property(133, String.class, "forwardVideo", false, "FORWARD_VIDEO");
        public final static Property ForwardVideoThumb = new Property(134, String.class, "forwardVideoThumb", false, "FORWARD_VIDEO_THUMB");
        public final static Property ForwardLink = new Property(135, String.class, "forwardLink", false, "FORWARD_LINK");
        public final static Property ForwardLinkTitle = new Property(136, String.class, "forwardLinkTitle", false, "FORWARD_LINK_TITLE");
        public final static Property ForwardLinkText = new Property(137, String.class, "forwardLinkText", false, "FORWARD_LINK_TEXT");
        public final static Property ForwardLinkImg = new Property(138, String.class, "forwardLinkImg", false, "FORWARD_LINK_IMG");
    }


    public DraftDao(DaoConfig config) {
        super(config);
    }

    public DraftDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"DRAFT\" (" + //
                "\"DRAFT_ID\" TEXT PRIMARY KEY NOT NULL UNIQUE ," + // 0: draftId
                "\"TIME\" INTEGER NOT NULL ," + // 1: time
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"SHOW\" INTEGER NOT NULL ," + // 3: show
                "\"COMMENT_PID\" TEXT," + // 4: commentPid
                "\"REPLY_CID\" TEXT," + // 5: replyCid
                "\"REPLY_REPLY_ID\" TEXT," + // 6: replyReplyId
                "\"TEXT\" TEXT," + // 7: text
                "\"SUMMARY\" TEXT," + // 8: summary
                "\"RICH\" TEXT," + // 9: rich
                "\"COMMENT_UID\" TEXT," + // 10: commentUid
                "\"COMMENT_NICK\" TEXT," + // 11: commentNick
                "\"F_TEXT\" TEXT," + // 12: fText
                "\"F_SUMMARY\" TEXT," + // 13: fSummary
                "\"F_RICH\" TEXT," + // 14: fRich
                "\"C_TEXT\" TEXT," + // 15: cText
                "\"C_SUMMARY\" TEXT," + // 16: cSummary
                "\"C_RICH\" TEXT," + // 17: cRich
                "\"R_TEXT\" TEXT," + // 18: rText
                "\"R_SUMMARY\" TEXT," + // 19: rSummary
                "\"R_RICH\" TEXT," + // 20: rRich
                "\"PLACEID\" TEXT," + // 21: placeid
                "\"PLACE\" TEXT," + // 22: place
                "\"LATITUDE\" TEXT," + // 23: latitude
                "\"LONGITUDE\" TEXT," + // 24: longitude
                "\"AS_COMMENT\" INTEGER NOT NULL ," + // 25: asComment
                "\"AS_REPOST\" INTEGER NOT NULL ," + // 26: asRepost
                "\"PIC1\" TEXT," + // 27: pic1
                "\"PIC1_TMP\" TEXT," + // 28: pic1Tmp
                "\"PIC1_WIDTH\" INTEGER," + // 29: pic1Width
                "\"PIC1_HEIGHT\" INTEGER," + // 30: pic1Height
                "\"PIC1_MIMETYPE\" TEXT," + // 31: pic1Mimetype
                "\"PIC1_KEY\" TEXT," + // 32: pic1Key
                "\"PIC1_URL\" TEXT," + // 33: pic1Url
                "\"PIC2\" TEXT," + // 34: pic2
                "\"PIC2_TMP\" TEXT," + // 35: pic2Tmp
                "\"PIC2_WIDTH\" INTEGER," + // 36: pic2Width
                "\"PIC2_HEIGHT\" INTEGER," + // 37: pic2Height
                "\"PIC2_MIMETYPE\" TEXT," + // 38: pic2Mimetype
                "\"PIC2_KEY\" TEXT," + // 39: pic2Key
                "\"PIC2_URL\" TEXT," + // 40: pic2Url
                "\"PIC3\" TEXT," + // 41: pic3
                "\"PIC3_TMP\" TEXT," + // 42: pic3Tmp
                "\"PIC3_WIDTH\" INTEGER," + // 43: pic3Width
                "\"PIC3_HEIGHT\" INTEGER," + // 44: pic3Height
                "\"PIC3_MIMETYPE\" TEXT," + // 45: pic3Mimetype
                "\"PIC3_KEY\" TEXT," + // 46: pic3Key
                "\"PIC3_URL\" TEXT," + // 47: pic3Url
                "\"PIC4\" TEXT," + // 48: pic4
                "\"PIC4_TMP\" TEXT," + // 49: pic4Tmp
                "\"PIC4_WIDTH\" INTEGER," + // 50: pic4Width
                "\"PIC4_HEIGHT\" INTEGER," + // 51: pic4Height
                "\"PIC4_MIMETYPE\" TEXT," + // 52: pic4Mimetype
                "\"PIC4_KEY\" TEXT," + // 53: pic4Key
                "\"PIC4_URL\" TEXT," + // 54: pic4Url
                "\"PIC5\" TEXT," + // 55: pic5
                "\"PIC5_TMP\" TEXT," + // 56: pic5Tmp
                "\"PIC5_WIDTH\" INTEGER," + // 57: pic5Width
                "\"PIC5_HEIGHT\" INTEGER," + // 58: pic5Height
                "\"PIC5_MIMETYPE\" TEXT," + // 59: pic5Mimetype
                "\"PIC5_KEY\" TEXT," + // 60: pic5Key
                "\"PIC5_URL\" TEXT," + // 61: pic5Url
                "\"PIC6\" TEXT," + // 62: pic6
                "\"PIC6_TMP\" TEXT," + // 63: pic6Tmp
                "\"PIC6_WIDTH\" INTEGER," + // 64: pic6Width
                "\"PIC6_HEIGHT\" INTEGER," + // 65: pic6Height
                "\"PIC6_MIMETYPE\" TEXT," + // 66: pic6Mimetype
                "\"PIC6_KEY\" TEXT," + // 67: pic6Key
                "\"PIC6_URL\" TEXT," + // 68: pic6Url
                "\"PIC7\" TEXT," + // 69: pic7
                "\"PIC7_TMP\" TEXT," + // 70: pic7Tmp
                "\"PIC7_WIDTH\" INTEGER," + // 71: pic7Width
                "\"PIC7_HEIGHT\" INTEGER," + // 72: pic7Height
                "\"PIC7_MIMETYPE\" TEXT," + // 73: pic7Mimetype
                "\"PIC7_KEY\" TEXT," + // 74: pic7Key
                "\"PIC7_URL\" TEXT," + // 75: pic7Url
                "\"PIC8\" TEXT," + // 76: pic8
                "\"PIC8_TMP\" TEXT," + // 77: pic8Tmp
                "\"PIC8_WIDTH\" INTEGER," + // 78: pic8Width
                "\"PIC8_HEIGHT\" INTEGER," + // 79: pic8Height
                "\"PIC8_MIMETYPE\" TEXT," + // 80: pic8Mimetype
                "\"PIC8_KEY\" TEXT," + // 81: pic8Key
                "\"PIC8_URL\" TEXT," + // 82: pic8Url
                "\"PIC9\" TEXT," + // 83: pic9
                "\"PIC9_TMP\" TEXT," + // 84: pic9Tmp
                "\"PIC9_WIDTH\" INTEGER," + // 85: pic9Width
                "\"PIC9_HEIGHT\" INTEGER," + // 86: pic9Height
                "\"PIC9_MIMETYPE\" TEXT," + // 87: pic9Mimetype
                "\"PIC9_KEY\" TEXT," + // 88: pic9Key
                "\"PIC9_URL\" TEXT," + // 89: pic9Url
                "\"VIDEO\" TEXT," + // 90: video
                "\"VIDEO_TMP\" TEXT," + // 91: videoTmp
                "\"VIDEO_MIMETYPE\" TEXT," + // 92: videoMimetype
                "\"VIDEO_DUR\" INTEGER," + // 93: videoDur
                "\"VIDEO_KEY\" TEXT," + // 94: videoKey
                "\"VIDEO_URL\" TEXT," + // 95: videoUrl
                "\"VIDEO_THUMB\" TEXT," + // 96: videoThumb
                "\"VIDEO_THUMB_TMP\" TEXT," + // 97: videoThumbTmp
                "\"VIDEO_THUMB_KEY\" TEXT," + // 98: videoThumbKey
                "\"VIDEO_THUMB_URL\" TEXT," + // 99: videoThumbUrl
                "\"VIDEO_WIDTH\" INTEGER," + // 100: videoWidth
                "\"VIDEO_HEIGHT\" INTEGER," + // 101: videoHeight
                "\"FORWARD_PID\" TEXT," + // 102: forwardPid
                "\"FORWARD_DELETED\" INTEGER," + // 103: forwardDeleted
                "\"FORWARD_UID\" TEXT," + // 104: forwardUid
                "\"FORWARD_NICK\" TEXT," + // 105: forwardNick
                "\"FORWARD_HEAD\" TEXT," + // 106: forwardHead
                "\"FORWARD_TYPE\" INTEGER," + // 107: forwardType
                "\"FORWARD_LIKE_COUNT\" INTEGER," + // 108: forwardLikeCount
                "\"FORWARD_LIKE_VALUE\" INTEGER," + // 109: forwardLikeValue
                "\"FORWARD_COMMENT_COUNT\" INTEGER," + // 110: forwardCommentCount
                "\"FORWARD_FORWARD_COUNT\" INTEGER," + // 111: forwardForwardCount
                "\"FORWARD_TEXT\" TEXT," + // 112: forwardText
                "\"FORWARD_SUMMARY\" TEXT," + // 113: forwardSummary
                "\"FORWARD_RICH\" TEXT," + // 114: forwardRich
                "\"FORWARD_PIC1\" TEXT," + // 115: forwardPic1
                "\"FORWARD_PIC2\" TEXT," + // 116: forwardPic2
                "\"FORWARD_PIC3\" TEXT," + // 117: forwardPic3
                "\"FORWARD_PIC4\" TEXT," + // 118: forwardPic4
                "\"FORWARD_PIC5\" TEXT," + // 119: forwardPic5
                "\"FORWARD_PIC6\" TEXT," + // 120: forwardPic6
                "\"FORWARD_PIC7\" TEXT," + // 121: forwardPic7
                "\"FORWARD_PIC8\" TEXT," + // 122: forwardPic8
                "\"FORWARD_PIC9\" TEXT," + // 123: forwardPic9
                "\"FORWARD_PIC1_LARGE\" TEXT," + // 124: forwardPic1Large
                "\"FORWARD_PIC2_LARGE\" TEXT," + // 125: forwardPic2Large
                "\"FORWARD_PIC3_LARGE\" TEXT," + // 126: forwardPic3Large
                "\"FORWARD_PIC4_LARGE\" TEXT," + // 127: forwardPic4Large
                "\"FORWARD_PIC5_LARGE\" TEXT," + // 128: forwardPic5Large
                "\"FORWARD_PIC6_LARGE\" TEXT," + // 129: forwardPic6Large
                "\"FORWARD_PIC7_LARGE\" TEXT," + // 130: forwardPic7Large
                "\"FORWARD_PIC8_LARGE\" TEXT," + // 131: forwardPic8Large
                "\"FORWARD_PIC9_LARGE\" TEXT," + // 132: forwardPic9Large
                "\"FORWARD_VIDEO\" TEXT," + // 133: forwardVideo
                "\"FORWARD_VIDEO_THUMB\" TEXT," + // 134: forwardVideoThumb
                "\"FORWARD_LINK\" TEXT," + // 135: forwardLink
                "\"FORWARD_LINK_TITLE\" TEXT," + // 136: forwardLinkTitle
                "\"FORWARD_LINK_TEXT\" TEXT," + // 137: forwardLinkText
                "\"FORWARD_LINK_IMG\" TEXT);"); // 138: forwardLinkImg
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DRAFT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Draft entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getDraftId());
        stmt.bindLong(2, entity.getTime());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getShow() ? 1L : 0L);

        String commentPid = entity.getCommentPid();
        if (commentPid != null) {
            stmt.bindString(5, commentPid);
        }

        String replyCid = entity.getReplyCid();
        if (replyCid != null) {
            stmt.bindString(6, replyCid);
        }

        String replyReplyId = entity.getReplyReplyId();
        if (replyReplyId != null) {
            stmt.bindString(7, replyReplyId);
        }

        String text = entity.getText();
        if (text != null) {
            stmt.bindString(8, text);
        }

        String summary = entity.getSummary();
        if (summary != null) {
            stmt.bindString(9, summary);
        }

        String rich = entity.getRich();
        if (rich != null) {
            stmt.bindString(10, rich);
        }

        String commentUid = entity.getCommentUid();
        if (commentUid != null) {
            stmt.bindString(11, commentUid);
        }

        String commentNick = entity.getCommentNick();
        if (commentNick != null) {
            stmt.bindString(12, commentNick);
        }

        String fText = entity.getFText();
        if (fText != null) {
            stmt.bindString(13, fText);
        }

        String fSummary = entity.getFSummary();
        if (fSummary != null) {
            stmt.bindString(14, fSummary);
        }

        String fRich = entity.getFRich();
        if (fRich != null) {
            stmt.bindString(15, fRich);
        }

        String cText = entity.getCText();
        if (cText != null) {
            stmt.bindString(16, cText);
        }

        String cSummary = entity.getCSummary();
        if (cSummary != null) {
            stmt.bindString(17, cSummary);
        }

        String cRich = entity.getCRich();
        if (cRich != null) {
            stmt.bindString(18, cRich);
        }

        String rText = entity.getRText();
        if (rText != null) {
            stmt.bindString(19, rText);
        }

        String rSummary = entity.getRSummary();
        if (rSummary != null) {
            stmt.bindString(20, rSummary);
        }

        String rRich = entity.getRRich();
        if (rRich != null) {
            stmt.bindString(21, rRich);
        }

        String placeid = entity.getPlaceid();
        if (placeid != null) {
            stmt.bindString(22, placeid);
        }

        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(23, place);
        }

        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(24, latitude);
        }

        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(25, longitude);
        }
        stmt.bindLong(26, entity.getAsComment() ? 1L : 0L);
        stmt.bindLong(27, entity.getAsRepost() ? 1L : 0L);

        String pic1 = entity.getPic1();
        if (pic1 != null) {
            stmt.bindString(28, pic1);
        }

        String pic1Tmp = entity.getPic1Tmp();
        if (pic1Tmp != null) {
            stmt.bindString(29, pic1Tmp);
        }

        Integer pic1Width = entity.getPic1Width();
        if (pic1Width != null) {
            stmt.bindLong(30, pic1Width);
        }

        Integer pic1Height = entity.getPic1Height();
        if (pic1Height != null) {
            stmt.bindLong(31, pic1Height);
        }

        String pic1Mimetype = entity.getPic1Mimetype();
        if (pic1Mimetype != null) {
            stmt.bindString(32, pic1Mimetype);
        }

        String pic1Key = entity.getPic1Key();
        if (pic1Key != null) {
            stmt.bindString(33, pic1Key);
        }

        String pic1Url = entity.getPic1Url();
        if (pic1Url != null) {
            stmt.bindString(34, pic1Url);
        }

        String pic2 = entity.getPic2();
        if (pic2 != null) {
            stmt.bindString(35, pic2);
        }

        String pic2Tmp = entity.getPic2Tmp();
        if (pic2Tmp != null) {
            stmt.bindString(36, pic2Tmp);
        }

        Integer pic2Width = entity.getPic2Width();
        if (pic2Width != null) {
            stmt.bindLong(37, pic2Width);
        }

        Integer pic2Height = entity.getPic2Height();
        if (pic2Height != null) {
            stmt.bindLong(38, pic2Height);
        }

        String pic2Mimetype = entity.getPic2Mimetype();
        if (pic2Mimetype != null) {
            stmt.bindString(39, pic2Mimetype);
        }

        String pic2Key = entity.getPic2Key();
        if (pic2Key != null) {
            stmt.bindString(40, pic2Key);
        }

        String pic2Url = entity.getPic2Url();
        if (pic2Url != null) {
            stmt.bindString(41, pic2Url);
        }

        String pic3 = entity.getPic3();
        if (pic3 != null) {
            stmt.bindString(42, pic3);
        }

        String pic3Tmp = entity.getPic3Tmp();
        if (pic3Tmp != null) {
            stmt.bindString(43, pic3Tmp);
        }

        Integer pic3Width = entity.getPic3Width();
        if (pic3Width != null) {
            stmt.bindLong(44, pic3Width);
        }

        Integer pic3Height = entity.getPic3Height();
        if (pic3Height != null) {
            stmt.bindLong(45, pic3Height);
        }

        String pic3Mimetype = entity.getPic3Mimetype();
        if (pic3Mimetype != null) {
            stmt.bindString(46, pic3Mimetype);
        }

        String pic3Key = entity.getPic3Key();
        if (pic3Key != null) {
            stmt.bindString(47, pic3Key);
        }

        String pic3Url = entity.getPic3Url();
        if (pic3Url != null) {
            stmt.bindString(48, pic3Url);
        }

        String pic4 = entity.getPic4();
        if (pic4 != null) {
            stmt.bindString(49, pic4);
        }

        String pic4Tmp = entity.getPic4Tmp();
        if (pic4Tmp != null) {
            stmt.bindString(50, pic4Tmp);
        }

        Integer pic4Width = entity.getPic4Width();
        if (pic4Width != null) {
            stmt.bindLong(51, pic4Width);
        }

        Integer pic4Height = entity.getPic4Height();
        if (pic4Height != null) {
            stmt.bindLong(52, pic4Height);
        }

        String pic4Mimetype = entity.getPic4Mimetype();
        if (pic4Mimetype != null) {
            stmt.bindString(53, pic4Mimetype);
        }

        String pic4Key = entity.getPic4Key();
        if (pic4Key != null) {
            stmt.bindString(54, pic4Key);
        }

        String pic4Url = entity.getPic4Url();
        if (pic4Url != null) {
            stmt.bindString(55, pic4Url);
        }

        String pic5 = entity.getPic5();
        if (pic5 != null) {
            stmt.bindString(56, pic5);
        }

        String pic5Tmp = entity.getPic5Tmp();
        if (pic5Tmp != null) {
            stmt.bindString(57, pic5Tmp);
        }

        Integer pic5Width = entity.getPic5Width();
        if (pic5Width != null) {
            stmt.bindLong(58, pic5Width);
        }

        Integer pic5Height = entity.getPic5Height();
        if (pic5Height != null) {
            stmt.bindLong(59, pic5Height);
        }

        String pic5Mimetype = entity.getPic5Mimetype();
        if (pic5Mimetype != null) {
            stmt.bindString(60, pic5Mimetype);
        }

        String pic5Key = entity.getPic5Key();
        if (pic5Key != null) {
            stmt.bindString(61, pic5Key);
        }

        String pic5Url = entity.getPic5Url();
        if (pic5Url != null) {
            stmt.bindString(62, pic5Url);
        }

        String pic6 = entity.getPic6();
        if (pic6 != null) {
            stmt.bindString(63, pic6);
        }

        String pic6Tmp = entity.getPic6Tmp();
        if (pic6Tmp != null) {
            stmt.bindString(64, pic6Tmp);
        }

        Integer pic6Width = entity.getPic6Width();
        if (pic6Width != null) {
            stmt.bindLong(65, pic6Width);
        }

        Integer pic6Height = entity.getPic6Height();
        if (pic6Height != null) {
            stmt.bindLong(66, pic6Height);
        }

        String pic6Mimetype = entity.getPic6Mimetype();
        if (pic6Mimetype != null) {
            stmt.bindString(67, pic6Mimetype);
        }

        String pic6Key = entity.getPic6Key();
        if (pic6Key != null) {
            stmt.bindString(68, pic6Key);
        }

        String pic6Url = entity.getPic6Url();
        if (pic6Url != null) {
            stmt.bindString(69, pic6Url);
        }

        String pic7 = entity.getPic7();
        if (pic7 != null) {
            stmt.bindString(70, pic7);
        }

        String pic7Tmp = entity.getPic7Tmp();
        if (pic7Tmp != null) {
            stmt.bindString(71, pic7Tmp);
        }

        Integer pic7Width = entity.getPic7Width();
        if (pic7Width != null) {
            stmt.bindLong(72, pic7Width);
        }

        Integer pic7Height = entity.getPic7Height();
        if (pic7Height != null) {
            stmt.bindLong(73, pic7Height);
        }

        String pic7Mimetype = entity.getPic7Mimetype();
        if (pic7Mimetype != null) {
            stmt.bindString(74, pic7Mimetype);
        }

        String pic7Key = entity.getPic7Key();
        if (pic7Key != null) {
            stmt.bindString(75, pic7Key);
        }

        String pic7Url = entity.getPic7Url();
        if (pic7Url != null) {
            stmt.bindString(76, pic7Url);
        }

        String pic8 = entity.getPic8();
        if (pic8 != null) {
            stmt.bindString(77, pic8);
        }

        String pic8Tmp = entity.getPic8Tmp();
        if (pic8Tmp != null) {
            stmt.bindString(78, pic8Tmp);
        }

        Integer pic8Width = entity.getPic8Width();
        if (pic8Width != null) {
            stmt.bindLong(79, pic8Width);
        }

        Integer pic8Height = entity.getPic8Height();
        if (pic8Height != null) {
            stmt.bindLong(80, pic8Height);
        }

        String pic8Mimetype = entity.getPic8Mimetype();
        if (pic8Mimetype != null) {
            stmt.bindString(81, pic8Mimetype);
        }

        String pic8Key = entity.getPic8Key();
        if (pic8Key != null) {
            stmt.bindString(82, pic8Key);
        }

        String pic8Url = entity.getPic8Url();
        if (pic8Url != null) {
            stmt.bindString(83, pic8Url);
        }

        String pic9 = entity.getPic9();
        if (pic9 != null) {
            stmt.bindString(84, pic9);
        }

        String pic9Tmp = entity.getPic9Tmp();
        if (pic9Tmp != null) {
            stmt.bindString(85, pic9Tmp);
        }

        Integer pic9Width = entity.getPic9Width();
        if (pic9Width != null) {
            stmt.bindLong(86, pic9Width);
        }

        Integer pic9Height = entity.getPic9Height();
        if (pic9Height != null) {
            stmt.bindLong(87, pic9Height);
        }

        String pic9Mimetype = entity.getPic9Mimetype();
        if (pic9Mimetype != null) {
            stmt.bindString(88, pic9Mimetype);
        }

        String pic9Key = entity.getPic9Key();
        if (pic9Key != null) {
            stmt.bindString(89, pic9Key);
        }

        String pic9Url = entity.getPic9Url();
        if (pic9Url != null) {
            stmt.bindString(90, pic9Url);
        }

        String video = entity.getVideo();
        if (video != null) {
            stmt.bindString(91, video);
        }

        String videoTmp = entity.getVideoTmp();
        if (videoTmp != null) {
            stmt.bindString(92, videoTmp);
        }

        String videoMimetype = entity.getVideoMimetype();
        if (videoMimetype != null) {
            stmt.bindString(93, videoMimetype);
        }

        Long videoDur = entity.getVideoDur();
        if (videoDur != null) {
            stmt.bindLong(94, videoDur);
        }

        String videoKey = entity.getVideoKey();
        if (videoKey != null) {
            stmt.bindString(95, videoKey);
        }

        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(96, videoUrl);
        }

        String videoThumb = entity.getVideoThumb();
        if (videoThumb != null) {
            stmt.bindString(97, videoThumb);
        }

        String videoThumbTmp = entity.getVideoThumbTmp();
        if (videoThumbTmp != null) {
            stmt.bindString(98, videoThumbTmp);
        }

        String videoThumbKey = entity.getVideoThumbKey();
        if (videoThumbKey != null) {
            stmt.bindString(99, videoThumbKey);
        }

        String videoThumbUrl = entity.getVideoThumbUrl();
        if (videoThumbUrl != null) {
            stmt.bindString(100, videoThumbUrl);
        }

        Integer videoWidth = entity.getVideoWidth();
        if (videoWidth != null) {
            stmt.bindLong(101, videoWidth);
        }

        Integer videoHeight = entity.getVideoHeight();
        if (videoHeight != null) {
            stmt.bindLong(102, videoHeight);
        }

        String forwardPid = entity.getForwardPid();
        if (forwardPid != null) {
            stmt.bindString(103, forwardPid);
        }

        Boolean forwardDeleted = entity.getForwardDeleted();
        if (forwardDeleted != null) {
            stmt.bindLong(104, forwardDeleted ? 1L : 0L);
        }

        String forwardUid = entity.getForwardUid();
        if (forwardUid != null) {
            stmt.bindString(105, forwardUid);
        }

        String forwardNick = entity.getForwardNick();
        if (forwardNick != null) {
            stmt.bindString(106, forwardNick);
        }

        String forwardHead = entity.getForwardHead();
        if (forwardHead != null) {
            stmt.bindString(107, forwardHead);
        }

        Byte forwardType = entity.getForwardType();
        if (forwardType != null) {
            stmt.bindLong(108, forwardType);
        }

        Long forwardLikeCount = entity.getForwardLikeCount();
        if (forwardLikeCount != null) {
            stmt.bindLong(109, forwardLikeCount);
        }

        Integer forwardLikeValue = entity.getForwardLikeValue();
        if (forwardLikeValue != null) {
            stmt.bindLong(110, forwardLikeValue);
        }

        Integer forwardCommentCount = entity.getForwardCommentCount();
        if (forwardCommentCount != null) {
            stmt.bindLong(111, forwardCommentCount);
        }

        Integer forwardForwardCount = entity.getForwardForwardCount();
        if (forwardForwardCount != null) {
            stmt.bindLong(112, forwardForwardCount);
        }

        String forwardText = entity.getForwardText();
        if (forwardText != null) {
            stmt.bindString(113, forwardText);
        }

        String forwardSummary = entity.getForwardSummary();
        if (forwardSummary != null) {
            stmt.bindString(114, forwardSummary);
        }

        String forwardRich = entity.getForwardRich();
        if (forwardRich != null) {
            stmt.bindString(115, forwardRich);
        }

        String forwardPic1 = entity.getForwardPic1();
        if (forwardPic1 != null) {
            stmt.bindString(116, forwardPic1);
        }

        String forwardPic2 = entity.getForwardPic2();
        if (forwardPic2 != null) {
            stmt.bindString(117, forwardPic2);
        }

        String forwardPic3 = entity.getForwardPic3();
        if (forwardPic3 != null) {
            stmt.bindString(118, forwardPic3);
        }

        String forwardPic4 = entity.getForwardPic4();
        if (forwardPic4 != null) {
            stmt.bindString(119, forwardPic4);
        }

        String forwardPic5 = entity.getForwardPic5();
        if (forwardPic5 != null) {
            stmt.bindString(120, forwardPic5);
        }

        String forwardPic6 = entity.getForwardPic6();
        if (forwardPic6 != null) {
            stmt.bindString(121, forwardPic6);
        }

        String forwardPic7 = entity.getForwardPic7();
        if (forwardPic7 != null) {
            stmt.bindString(122, forwardPic7);
        }

        String forwardPic8 = entity.getForwardPic8();
        if (forwardPic8 != null) {
            stmt.bindString(123, forwardPic8);
        }

        String forwardPic9 = entity.getForwardPic9();
        if (forwardPic9 != null) {
            stmt.bindString(124, forwardPic9);
        }

        String forwardPic1Large = entity.getForwardPic1Large();
        if (forwardPic1Large != null) {
            stmt.bindString(125, forwardPic1Large);
        }

        String forwardPic2Large = entity.getForwardPic2Large();
        if (forwardPic2Large != null) {
            stmt.bindString(126, forwardPic2Large);
        }

        String forwardPic3Large = entity.getForwardPic3Large();
        if (forwardPic3Large != null) {
            stmt.bindString(127, forwardPic3Large);
        }

        String forwardPic4Large = entity.getForwardPic4Large();
        if (forwardPic4Large != null) {
            stmt.bindString(128, forwardPic4Large);
        }

        String forwardPic5Large = entity.getForwardPic5Large();
        if (forwardPic5Large != null) {
            stmt.bindString(129, forwardPic5Large);
        }

        String forwardPic6Large = entity.getForwardPic6Large();
        if (forwardPic6Large != null) {
            stmt.bindString(130, forwardPic6Large);
        }

        String forwardPic7Large = entity.getForwardPic7Large();
        if (forwardPic7Large != null) {
            stmt.bindString(131, forwardPic7Large);
        }

        String forwardPic8Large = entity.getForwardPic8Large();
        if (forwardPic8Large != null) {
            stmt.bindString(132, forwardPic8Large);
        }

        String forwardPic9Large = entity.getForwardPic9Large();
        if (forwardPic9Large != null) {
            stmt.bindString(133, forwardPic9Large);
        }

        String forwardVideo = entity.getForwardVideo();
        if (forwardVideo != null) {
            stmt.bindString(134, forwardVideo);
        }

        String forwardVideoThumb = entity.getForwardVideoThumb();
        if (forwardVideoThumb != null) {
            stmt.bindString(135, forwardVideoThumb);
        }

        String forwardLink = entity.getForwardLink();
        if (forwardLink != null) {
            stmt.bindString(136, forwardLink);
        }

        String forwardLinkTitle = entity.getForwardLinkTitle();
        if (forwardLinkTitle != null) {
            stmt.bindString(137, forwardLinkTitle);
        }

        String forwardLinkText = entity.getForwardLinkText();
        if (forwardLinkText != null) {
            stmt.bindString(138, forwardLinkText);
        }

        String forwardLinkImg = entity.getForwardLinkImg();
        if (forwardLinkImg != null) {
            stmt.bindString(139, forwardLinkImg);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Draft entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getDraftId());
        stmt.bindLong(2, entity.getTime());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getShow() ? 1L : 0L);

        String commentPid = entity.getCommentPid();
        if (commentPid != null) {
            stmt.bindString(5, commentPid);
        }

        String replyCid = entity.getReplyCid();
        if (replyCid != null) {
            stmt.bindString(6, replyCid);
        }

        String replyReplyId = entity.getReplyReplyId();
        if (replyReplyId != null) {
            stmt.bindString(7, replyReplyId);
        }

        String text = entity.getText();
        if (text != null) {
            stmt.bindString(8, text);
        }

        String summary = entity.getSummary();
        if (summary != null) {
            stmt.bindString(9, summary);
        }

        String rich = entity.getRich();
        if (rich != null) {
            stmt.bindString(10, rich);
        }

        String commentUid = entity.getCommentUid();
        if (commentUid != null) {
            stmt.bindString(11, commentUid);
        }

        String commentNick = entity.getCommentNick();
        if (commentNick != null) {
            stmt.bindString(12, commentNick);
        }

        String fText = entity.getFText();
        if (fText != null) {
            stmt.bindString(13, fText);
        }

        String fSummary = entity.getFSummary();
        if (fSummary != null) {
            stmt.bindString(14, fSummary);
        }

        String fRich = entity.getFRich();
        if (fRich != null) {
            stmt.bindString(15, fRich);
        }

        String cText = entity.getCText();
        if (cText != null) {
            stmt.bindString(16, cText);
        }

        String cSummary = entity.getCSummary();
        if (cSummary != null) {
            stmt.bindString(17, cSummary);
        }

        String cRich = entity.getCRich();
        if (cRich != null) {
            stmt.bindString(18, cRich);
        }

        String rText = entity.getRText();
        if (rText != null) {
            stmt.bindString(19, rText);
        }

        String rSummary = entity.getRSummary();
        if (rSummary != null) {
            stmt.bindString(20, rSummary);
        }

        String rRich = entity.getRRich();
        if (rRich != null) {
            stmt.bindString(21, rRich);
        }

        String placeid = entity.getPlaceid();
        if (placeid != null) {
            stmt.bindString(22, placeid);
        }

        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(23, place);
        }

        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(24, latitude);
        }

        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(25, longitude);
        }
        stmt.bindLong(26, entity.getAsComment() ? 1L : 0L);
        stmt.bindLong(27, entity.getAsRepost() ? 1L : 0L);

        String pic1 = entity.getPic1();
        if (pic1 != null) {
            stmt.bindString(28, pic1);
        }

        String pic1Tmp = entity.getPic1Tmp();
        if (pic1Tmp != null) {
            stmt.bindString(29, pic1Tmp);
        }

        Integer pic1Width = entity.getPic1Width();
        if (pic1Width != null) {
            stmt.bindLong(30, pic1Width);
        }

        Integer pic1Height = entity.getPic1Height();
        if (pic1Height != null) {
            stmt.bindLong(31, pic1Height);
        }

        String pic1Mimetype = entity.getPic1Mimetype();
        if (pic1Mimetype != null) {
            stmt.bindString(32, pic1Mimetype);
        }

        String pic1Key = entity.getPic1Key();
        if (pic1Key != null) {
            stmt.bindString(33, pic1Key);
        }

        String pic1Url = entity.getPic1Url();
        if (pic1Url != null) {
            stmt.bindString(34, pic1Url);
        }

        String pic2 = entity.getPic2();
        if (pic2 != null) {
            stmt.bindString(35, pic2);
        }

        String pic2Tmp = entity.getPic2Tmp();
        if (pic2Tmp != null) {
            stmt.bindString(36, pic2Tmp);
        }

        Integer pic2Width = entity.getPic2Width();
        if (pic2Width != null) {
            stmt.bindLong(37, pic2Width);
        }

        Integer pic2Height = entity.getPic2Height();
        if (pic2Height != null) {
            stmt.bindLong(38, pic2Height);
        }

        String pic2Mimetype = entity.getPic2Mimetype();
        if (pic2Mimetype != null) {
            stmt.bindString(39, pic2Mimetype);
        }

        String pic2Key = entity.getPic2Key();
        if (pic2Key != null) {
            stmt.bindString(40, pic2Key);
        }

        String pic2Url = entity.getPic2Url();
        if (pic2Url != null) {
            stmt.bindString(41, pic2Url);
        }

        String pic3 = entity.getPic3();
        if (pic3 != null) {
            stmt.bindString(42, pic3);
        }

        String pic3Tmp = entity.getPic3Tmp();
        if (pic3Tmp != null) {
            stmt.bindString(43, pic3Tmp);
        }

        Integer pic3Width = entity.getPic3Width();
        if (pic3Width != null) {
            stmt.bindLong(44, pic3Width);
        }

        Integer pic3Height = entity.getPic3Height();
        if (pic3Height != null) {
            stmt.bindLong(45, pic3Height);
        }

        String pic3Mimetype = entity.getPic3Mimetype();
        if (pic3Mimetype != null) {
            stmt.bindString(46, pic3Mimetype);
        }

        String pic3Key = entity.getPic3Key();
        if (pic3Key != null) {
            stmt.bindString(47, pic3Key);
        }

        String pic3Url = entity.getPic3Url();
        if (pic3Url != null) {
            stmt.bindString(48, pic3Url);
        }

        String pic4 = entity.getPic4();
        if (pic4 != null) {
            stmt.bindString(49, pic4);
        }

        String pic4Tmp = entity.getPic4Tmp();
        if (pic4Tmp != null) {
            stmt.bindString(50, pic4Tmp);
        }

        Integer pic4Width = entity.getPic4Width();
        if (pic4Width != null) {
            stmt.bindLong(51, pic4Width);
        }

        Integer pic4Height = entity.getPic4Height();
        if (pic4Height != null) {
            stmt.bindLong(52, pic4Height);
        }

        String pic4Mimetype = entity.getPic4Mimetype();
        if (pic4Mimetype != null) {
            stmt.bindString(53, pic4Mimetype);
        }

        String pic4Key = entity.getPic4Key();
        if (pic4Key != null) {
            stmt.bindString(54, pic4Key);
        }

        String pic4Url = entity.getPic4Url();
        if (pic4Url != null) {
            stmt.bindString(55, pic4Url);
        }

        String pic5 = entity.getPic5();
        if (pic5 != null) {
            stmt.bindString(56, pic5);
        }

        String pic5Tmp = entity.getPic5Tmp();
        if (pic5Tmp != null) {
            stmt.bindString(57, pic5Tmp);
        }

        Integer pic5Width = entity.getPic5Width();
        if (pic5Width != null) {
            stmt.bindLong(58, pic5Width);
        }

        Integer pic5Height = entity.getPic5Height();
        if (pic5Height != null) {
            stmt.bindLong(59, pic5Height);
        }

        String pic5Mimetype = entity.getPic5Mimetype();
        if (pic5Mimetype != null) {
            stmt.bindString(60, pic5Mimetype);
        }

        String pic5Key = entity.getPic5Key();
        if (pic5Key != null) {
            stmt.bindString(61, pic5Key);
        }

        String pic5Url = entity.getPic5Url();
        if (pic5Url != null) {
            stmt.bindString(62, pic5Url);
        }

        String pic6 = entity.getPic6();
        if (pic6 != null) {
            stmt.bindString(63, pic6);
        }

        String pic6Tmp = entity.getPic6Tmp();
        if (pic6Tmp != null) {
            stmt.bindString(64, pic6Tmp);
        }

        Integer pic6Width = entity.getPic6Width();
        if (pic6Width != null) {
            stmt.bindLong(65, pic6Width);
        }

        Integer pic6Height = entity.getPic6Height();
        if (pic6Height != null) {
            stmt.bindLong(66, pic6Height);
        }

        String pic6Mimetype = entity.getPic6Mimetype();
        if (pic6Mimetype != null) {
            stmt.bindString(67, pic6Mimetype);
        }

        String pic6Key = entity.getPic6Key();
        if (pic6Key != null) {
            stmt.bindString(68, pic6Key);
        }

        String pic6Url = entity.getPic6Url();
        if (pic6Url != null) {
            stmt.bindString(69, pic6Url);
        }

        String pic7 = entity.getPic7();
        if (pic7 != null) {
            stmt.bindString(70, pic7);
        }

        String pic7Tmp = entity.getPic7Tmp();
        if (pic7Tmp != null) {
            stmt.bindString(71, pic7Tmp);
        }

        Integer pic7Width = entity.getPic7Width();
        if (pic7Width != null) {
            stmt.bindLong(72, pic7Width);
        }

        Integer pic7Height = entity.getPic7Height();
        if (pic7Height != null) {
            stmt.bindLong(73, pic7Height);
        }

        String pic7Mimetype = entity.getPic7Mimetype();
        if (pic7Mimetype != null) {
            stmt.bindString(74, pic7Mimetype);
        }

        String pic7Key = entity.getPic7Key();
        if (pic7Key != null) {
            stmt.bindString(75, pic7Key);
        }

        String pic7Url = entity.getPic7Url();
        if (pic7Url != null) {
            stmt.bindString(76, pic7Url);
        }

        String pic8 = entity.getPic8();
        if (pic8 != null) {
            stmt.bindString(77, pic8);
        }

        String pic8Tmp = entity.getPic8Tmp();
        if (pic8Tmp != null) {
            stmt.bindString(78, pic8Tmp);
        }

        Integer pic8Width = entity.getPic8Width();
        if (pic8Width != null) {
            stmt.bindLong(79, pic8Width);
        }

        Integer pic8Height = entity.getPic8Height();
        if (pic8Height != null) {
            stmt.bindLong(80, pic8Height);
        }

        String pic8Mimetype = entity.getPic8Mimetype();
        if (pic8Mimetype != null) {
            stmt.bindString(81, pic8Mimetype);
        }

        String pic8Key = entity.getPic8Key();
        if (pic8Key != null) {
            stmt.bindString(82, pic8Key);
        }

        String pic8Url = entity.getPic8Url();
        if (pic8Url != null) {
            stmt.bindString(83, pic8Url);
        }

        String pic9 = entity.getPic9();
        if (pic9 != null) {
            stmt.bindString(84, pic9);
        }

        String pic9Tmp = entity.getPic9Tmp();
        if (pic9Tmp != null) {
            stmt.bindString(85, pic9Tmp);
        }

        Integer pic9Width = entity.getPic9Width();
        if (pic9Width != null) {
            stmt.bindLong(86, pic9Width);
        }

        Integer pic9Height = entity.getPic9Height();
        if (pic9Height != null) {
            stmt.bindLong(87, pic9Height);
        }

        String pic9Mimetype = entity.getPic9Mimetype();
        if (pic9Mimetype != null) {
            stmt.bindString(88, pic9Mimetype);
        }

        String pic9Key = entity.getPic9Key();
        if (pic9Key != null) {
            stmt.bindString(89, pic9Key);
        }

        String pic9Url = entity.getPic9Url();
        if (pic9Url != null) {
            stmt.bindString(90, pic9Url);
        }

        String video = entity.getVideo();
        if (video != null) {
            stmt.bindString(91, video);
        }

        String videoTmp = entity.getVideoTmp();
        if (videoTmp != null) {
            stmt.bindString(92, videoTmp);
        }

        String videoMimetype = entity.getVideoMimetype();
        if (videoMimetype != null) {
            stmt.bindString(93, videoMimetype);
        }

        Long videoDur = entity.getVideoDur();
        if (videoDur != null) {
            stmt.bindLong(94, videoDur);
        }

        String videoKey = entity.getVideoKey();
        if (videoKey != null) {
            stmt.bindString(95, videoKey);
        }

        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(96, videoUrl);
        }

        String videoThumb = entity.getVideoThumb();
        if (videoThumb != null) {
            stmt.bindString(97, videoThumb);
        }

        String videoThumbTmp = entity.getVideoThumbTmp();
        if (videoThumbTmp != null) {
            stmt.bindString(98, videoThumbTmp);
        }

        String videoThumbKey = entity.getVideoThumbKey();
        if (videoThumbKey != null) {
            stmt.bindString(99, videoThumbKey);
        }

        String videoThumbUrl = entity.getVideoThumbUrl();
        if (videoThumbUrl != null) {
            stmt.bindString(100, videoThumbUrl);
        }

        Integer videoWidth = entity.getVideoWidth();
        if (videoWidth != null) {
            stmt.bindLong(101, videoWidth);
        }

        Integer videoHeight = entity.getVideoHeight();
        if (videoHeight != null) {
            stmt.bindLong(102, videoHeight);
        }

        String forwardPid = entity.getForwardPid();
        if (forwardPid != null) {
            stmt.bindString(103, forwardPid);
        }

        Boolean forwardDeleted = entity.getForwardDeleted();
        if (forwardDeleted != null) {
            stmt.bindLong(104, forwardDeleted ? 1L : 0L);
        }

        String forwardUid = entity.getForwardUid();
        if (forwardUid != null) {
            stmt.bindString(105, forwardUid);
        }

        String forwardNick = entity.getForwardNick();
        if (forwardNick != null) {
            stmt.bindString(106, forwardNick);
        }

        String forwardHead = entity.getForwardHead();
        if (forwardHead != null) {
            stmt.bindString(107, forwardHead);
        }

        Byte forwardType = entity.getForwardType();
        if (forwardType != null) {
            stmt.bindLong(108, forwardType);
        }

        Long forwardLikeCount = entity.getForwardLikeCount();
        if (forwardLikeCount != null) {
            stmt.bindLong(109, forwardLikeCount);
        }

        Integer forwardLikeValue = entity.getForwardLikeValue();
        if (forwardLikeValue != null) {
            stmt.bindLong(110, forwardLikeValue);
        }

        Integer forwardCommentCount = entity.getForwardCommentCount();
        if (forwardCommentCount != null) {
            stmt.bindLong(111, forwardCommentCount);
        }

        Integer forwardForwardCount = entity.getForwardForwardCount();
        if (forwardForwardCount != null) {
            stmt.bindLong(112, forwardForwardCount);
        }

        String forwardText = entity.getForwardText();
        if (forwardText != null) {
            stmt.bindString(113, forwardText);
        }

        String forwardSummary = entity.getForwardSummary();
        if (forwardSummary != null) {
            stmt.bindString(114, forwardSummary);
        }

        String forwardRich = entity.getForwardRich();
        if (forwardRich != null) {
            stmt.bindString(115, forwardRich);
        }

        String forwardPic1 = entity.getForwardPic1();
        if (forwardPic1 != null) {
            stmt.bindString(116, forwardPic1);
        }

        String forwardPic2 = entity.getForwardPic2();
        if (forwardPic2 != null) {
            stmt.bindString(117, forwardPic2);
        }

        String forwardPic3 = entity.getForwardPic3();
        if (forwardPic3 != null) {
            stmt.bindString(118, forwardPic3);
        }

        String forwardPic4 = entity.getForwardPic4();
        if (forwardPic4 != null) {
            stmt.bindString(119, forwardPic4);
        }

        String forwardPic5 = entity.getForwardPic5();
        if (forwardPic5 != null) {
            stmt.bindString(120, forwardPic5);
        }

        String forwardPic6 = entity.getForwardPic6();
        if (forwardPic6 != null) {
            stmt.bindString(121, forwardPic6);
        }

        String forwardPic7 = entity.getForwardPic7();
        if (forwardPic7 != null) {
            stmt.bindString(122, forwardPic7);
        }

        String forwardPic8 = entity.getForwardPic8();
        if (forwardPic8 != null) {
            stmt.bindString(123, forwardPic8);
        }

        String forwardPic9 = entity.getForwardPic9();
        if (forwardPic9 != null) {
            stmt.bindString(124, forwardPic9);
        }

        String forwardPic1Large = entity.getForwardPic1Large();
        if (forwardPic1Large != null) {
            stmt.bindString(125, forwardPic1Large);
        }

        String forwardPic2Large = entity.getForwardPic2Large();
        if (forwardPic2Large != null) {
            stmt.bindString(126, forwardPic2Large);
        }

        String forwardPic3Large = entity.getForwardPic3Large();
        if (forwardPic3Large != null) {
            stmt.bindString(127, forwardPic3Large);
        }

        String forwardPic4Large = entity.getForwardPic4Large();
        if (forwardPic4Large != null) {
            stmt.bindString(128, forwardPic4Large);
        }

        String forwardPic5Large = entity.getForwardPic5Large();
        if (forwardPic5Large != null) {
            stmt.bindString(129, forwardPic5Large);
        }

        String forwardPic6Large = entity.getForwardPic6Large();
        if (forwardPic6Large != null) {
            stmt.bindString(130, forwardPic6Large);
        }

        String forwardPic7Large = entity.getForwardPic7Large();
        if (forwardPic7Large != null) {
            stmt.bindString(131, forwardPic7Large);
        }

        String forwardPic8Large = entity.getForwardPic8Large();
        if (forwardPic8Large != null) {
            stmt.bindString(132, forwardPic8Large);
        }

        String forwardPic9Large = entity.getForwardPic9Large();
        if (forwardPic9Large != null) {
            stmt.bindString(133, forwardPic9Large);
        }

        String forwardVideo = entity.getForwardVideo();
        if (forwardVideo != null) {
            stmt.bindString(134, forwardVideo);
        }

        String forwardVideoThumb = entity.getForwardVideoThumb();
        if (forwardVideoThumb != null) {
            stmt.bindString(135, forwardVideoThumb);
        }

        String forwardLink = entity.getForwardLink();
        if (forwardLink != null) {
            stmt.bindString(136, forwardLink);
        }

        String forwardLinkTitle = entity.getForwardLinkTitle();
        if (forwardLinkTitle != null) {
            stmt.bindString(137, forwardLinkTitle);
        }

        String forwardLinkText = entity.getForwardLinkText();
        if (forwardLinkText != null) {
            stmt.bindString(138, forwardLinkText);
        }

        String forwardLinkImg = entity.getForwardLinkImg();
        if (forwardLinkImg != null) {
            stmt.bindString(139, forwardLinkImg);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }

    @Override
    public Draft readEntity(Cursor cursor, int offset) {
        String commentPid = cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4);
        String replyCid = cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5);
        String replyReplyId = cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6);
        String text = cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7);
        String summary = cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8);
        String rich = cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9);
        String commentUid = cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10);
        String commentNick = cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11);
        String fText = cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12);
        String fSummary = cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13);
        String fRich = cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14);
        String cText = cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15);
        String cSummary = cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16);
        String cRich = cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17);
        String rText = cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18);
        String rSummary = cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19);
        String rRich = cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20);
        String placeid = cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21);
        String place = cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22);
        String latitude = cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23);
        String longitude = cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24);

        Boolean asComment = cursor.getShort(offset + 25) != 0; // asComment
        Boolean asRepost = cursor.getShort(offset + 26) != 0; // asRepost

        String pic1 = cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27);
        String pic1Tmp = cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28);
        Integer pic1Width = cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29);
        Integer pic1Height = cursor.isNull(offset + 30) ? null : cursor.getInt(offset + 30);
        String pic1Mimetype = cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31);
        String pic1Key = cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32);
        String pic1Url = cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33);
        String pic2 = cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34);
        String pic2Tmp = cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35);
        Integer pic2Width = cursor.isNull(offset + 36) ? null : cursor.getInt(offset + 36);
        Integer pic2Height = cursor.isNull(offset + 37) ? null : cursor.getInt(offset + 37);
        String pic2Mimetype = cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38);
        String pic2Key = cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39);
        String pic2Url = cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40);
        String pic3 = cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41);
        String pic3Tmp = cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42);
        Integer pic3Width = cursor.isNull(offset + 43) ? null : cursor.getInt(offset + 43);
        Integer pic3Height = cursor.isNull(offset + 44) ? null : cursor.getInt(offset + 44);
        String pic3Mimetype = cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45);
        String pic3Key = cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46);
        String pic3Url = cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47);
        String pic4 = cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48);
        String pic4Tmp = cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49);
        Integer pic4Width = cursor.isNull(offset + 50) ? null : cursor.getInt(offset + 50);
        Integer pic4Height = cursor.isNull(offset + 51) ? null : cursor.getInt(offset + 51);
        String pic4Mimetype = cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52);
        String pic4Key = cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53);
        String pic4Url = cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54);
        String pic5 = cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55);
        String pic5Tmp = cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56);
        Integer pic5Width = cursor.isNull(offset + 57) ? null : cursor.getInt(offset + 57);
        Integer pic5Height = cursor.isNull(offset + 58) ? null : cursor.getInt(offset + 58);
        String pic5Mimetype = cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59);
        String pic5Key = cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60);
        String pic5Url = cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61);
        String pic6 = cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62);
        String pic6Tmp = cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63);
        Integer pic6Width = cursor.isNull(offset + 64) ? null : cursor.getInt(offset + 64);
        Integer pic6Height = cursor.isNull(offset + 65) ? null : cursor.getInt(offset + 65);
        String pic6Mimetype = cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66);
        String pic6Key = cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67);
        String pic6Url = cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68);
        String pic7 = cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69);
        String pic7Tmp = cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70);
        Integer pic7Width = cursor.isNull(offset + 71) ? null : cursor.getInt(offset + 71);
        Integer pic7Height = cursor.isNull(offset + 72) ? null : cursor.getInt(offset + 72);
        String pic7Mimetype = cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73);
        String pic7Key = cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74);
        String pic7Url = cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75);
        String pic8 = cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76);
        String pic8Tmp = cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77);
        Integer pic8Width = cursor.isNull(offset + 78) ? null : cursor.getInt(offset + 78);
        Integer pic8Height = cursor.isNull(offset + 79) ? null : cursor.getInt(offset + 79);
        String pic8Mimetype = cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80);
        String pic8Key = cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81);
        String pic8Url = cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82);
        String pic9 = cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83);
        String pic9Tmp = cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84);
        Integer pic9Width = cursor.isNull(offset + 85) ? null : cursor.getInt(offset + 85);
        Integer pic9Height = cursor.isNull(offset + 86) ? null : cursor.getInt(offset + 86);
        String pic9Mimetype = cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87);
        String pic9Key = cursor.isNull(offset + 88) ? null : cursor.getString(offset + 88);
        String pic9Url = cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89);
        String video = cursor.isNull(offset + 90) ? null : cursor.getString(offset + 90);
        String videoTmp = cursor.isNull(offset + 91) ? null : cursor.getString(offset + 91);
        String videoMimetype = cursor.isNull(offset + 92) ? null : cursor.getString(offset + 92);
        Long videoDur = cursor.isNull(offset + 93) ? null : cursor.getLong(offset + 93);
        String videoKey = cursor.isNull(offset + 94) ? null : cursor.getString(offset + 94);
        String videoUrl = cursor.isNull(offset + 95) ? null : cursor.getString(offset + 95);
        String videoThumb = cursor.isNull(offset + 96) ? null : cursor.getString(offset + 96);
        String videoThumbTmp = cursor.isNull(offset + 97) ? null : cursor.getString(offset + 97);
        String videoThumbKey = cursor.isNull(offset + 98) ? null : cursor.getString(offset + 98);
        String videoThumbUrl = cursor.isNull(offset + 99) ? null : cursor.getString(offset + 99);
        Integer videoWidth = cursor.isNull(offset + 100) ? null : cursor.getInt(offset + 100);
        Integer videoHeight = cursor.isNull(offset + 101) ? null : cursor.getInt(offset + 101);
        String forwardPid = cursor.isNull(offset + 102) ? null : cursor.getString(offset + 102);
        Boolean forwardDeleted = cursor.isNull(offset + 103) ? null : cursor.getShort(offset + 103) != 0;
        String forwardUid = cursor.isNull(offset + 104) ? null : cursor.getString(offset + 104);
        String forwardNick = cursor.isNull(offset + 105) ? null : cursor.getString(offset + 105);
        String forwardHead = cursor.isNull(offset + 106) ? null : cursor.getString(offset + 106);
        Byte forwardType = cursor.isNull(offset + 107) ? null : (byte) cursor.getShort(offset + 107);
        Long forwardLikeCount = cursor.isNull(offset + 108) ? null : cursor.getLong(offset + 108);
        Integer forwardLikeValue = cursor.isNull(offset + 109) ? null : cursor.getInt(offset + 109);
        Integer forwardCommentCount = cursor.isNull(offset + 110) ? null : cursor.getInt(offset + 110);
        Integer forwardForwardCount = cursor.isNull(offset + 111) ? null : cursor.getInt(offset + 111);
        String forwardText = cursor.isNull(offset + 112) ? null : cursor.getString(offset + 112);
        String forwardSummary = cursor.isNull(offset + 113) ? null : cursor.getString(offset + 113);
        String forwardRich = cursor.isNull(offset + 114) ? null : cursor.getString(offset + 114);
        String forwardPic1 = cursor.isNull(offset + 115) ? null : cursor.getString(offset + 115);
        String forwardPic2 = cursor.isNull(offset + 116) ? null : cursor.getString(offset + 116);
        String forwardPic3 = cursor.isNull(offset + 117) ? null : cursor.getString(offset + 117);
        String forwardPic4 = cursor.isNull(offset + 118) ? null : cursor.getString(offset + 118);
        String forwardPic5 = cursor.isNull(offset + 119) ? null : cursor.getString(offset + 119);
        String forwardPic6 = cursor.isNull(offset + 120) ? null : cursor.getString(offset + 120);
        String forwardPic7 = cursor.isNull(offset + 121) ? null : cursor.getString(offset + 121);
        String forwardPic8 = cursor.isNull(offset + 122) ? null : cursor.getString(offset + 122);
        String forwardPic9 = cursor.isNull(offset + 123) ? null : cursor.getString(offset + 123);
        String forwardPic1Large = cursor.isNull(offset + 124) ? null : cursor.getString(offset + 124);
        String forwardPic2Large = cursor.isNull(offset + 125) ? null : cursor.getString(offset + 125);
        String forwardPic3Large = cursor.isNull(offset + 126) ? null : cursor.getString(offset + 126);
        String forwardPic4Large = cursor.isNull(offset + 127) ? null : cursor.getString(offset + 127);
        String forwardPic5Large = cursor.isNull(offset + 128) ? null : cursor.getString(offset + 128);
        String forwardPic6Large = cursor.isNull(offset + 129) ? null : cursor.getString(offset + 129);
        String forwardPic7Large = cursor.isNull(offset + 130) ? null : cursor.getString(offset + 130);
        String forwardPic8Large = cursor.isNull(offset + 131) ? null : cursor.getString(offset + 131);
        String forwardPic9Large = cursor.isNull(offset + 132) ? null : cursor.getString(offset + 132);
        String forwardVideo = cursor.isNull(offset + 133) ? null : cursor.getString(offset + 133);
        String forwardVideoThumb = cursor.isNull(offset + 134) ? null : cursor.getString(offset + 134);
        String forwardLink = cursor.isNull(offset + 135) ? null : cursor.getString(offset + 135);
        String forwardLinkTitle = cursor.isNull(offset + 136) ? null : cursor.getString(offset + 136);
        String forwardLinkText = cursor.isNull(offset + 137) ? null : cursor.getString(offset + 137);
        String forwardLinkImg = cursor.isNull(offset + 138) ? null : cursor.getString(offset + 138);

        Draft entity = new Draft( //
                cursor.getString(offset + 0), // draftId
                cursor.getLong(offset + 1), // time
                (byte) cursor.getShort(offset + 2), // type
                cursor.getShort(offset + 3) != 0, // show
                commentPid,
                replyCid,
                replyReplyId,
                text,
                summary,
                rich,
                commentUid,
                commentNick,
                fText,
                fSummary,
                fRich,
                cText,
                cSummary,
                cRich,
                rText,
                rSummary,
                rRich,
                placeid,
                place,
                latitude,
                longitude,
                asComment,
                asRepost,
                pic1,
                pic1Tmp,
                pic1Width,
                pic1Height,
                pic1Mimetype,
                pic1Key,
                pic1Url,
                pic2,
                pic2Tmp,
                pic2Width,
                pic2Height,
                pic2Mimetype,
                pic2Key,
                pic2Url,
                pic3,
                pic3Tmp,
                pic3Width,
                pic3Height,
                pic3Mimetype,
                pic3Key,
                pic3Url,
                pic4,
                pic4Tmp,
                pic4Width,
                pic4Height,
                pic4Mimetype,
                pic4Key,
                pic4Url,
                pic5,
                pic5Tmp,
                pic5Width,
                pic5Height,
                pic5Mimetype,
                pic5Key,
                pic5Url,
                pic6,
                pic6Tmp,
                pic6Width,
                pic6Height,
                pic6Mimetype,
                pic6Key,
                pic6Url,
                pic7,
                pic7Tmp,
                pic7Width,
                pic7Height,
                pic7Mimetype,
                pic7Key,
                pic7Url,
                pic8,
                pic8Tmp,
                pic8Width,
                pic8Height,
                pic8Mimetype,
                pic8Key,
                pic8Url,
                pic9,
                pic9Tmp,
                pic9Width,
                pic9Height,
                pic9Mimetype,
                pic9Key,
                pic9Url,
                video,
                videoTmp,
                videoMimetype,
                videoDur,
                videoKey,
                videoUrl,
                videoThumb,
                videoThumbTmp,
                videoThumbKey,
                videoThumbUrl,
                videoWidth,
                videoHeight,
                forwardPid,
                forwardDeleted,
                forwardUid,
                forwardNick,
                forwardHead,
                forwardType,
                forwardLikeCount,
                forwardLikeValue,
                forwardCommentCount,
                forwardForwardCount,
                forwardText,
                forwardSummary,
                forwardRich,
                forwardPic1,
                forwardPic2,
                forwardPic3,
                forwardPic4,
                forwardPic5,
                forwardPic6,
                forwardPic7,
                forwardPic8,
                forwardPic9,
                forwardPic1Large,
                forwardPic2Large,
                forwardPic3Large,
                forwardPic4Large,
                forwardPic5Large,
                forwardPic6Large,
                forwardPic7Large,
                forwardPic8Large,
                forwardPic9Large,
                forwardVideo,
                forwardVideoThumb,
                forwardLink,
                forwardLinkTitle,
                forwardLinkText,
                forwardLinkImg
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Draft entity, int offset) {
        entity.setDraftId(cursor.getString(offset + 0));
        entity.setTime(cursor.getLong(offset + 1));
        entity.setType((byte) cursor.getShort(offset + 2));
        entity.setShow(cursor.getShort(offset + 3) != 0);
        entity.setCommentPid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setReplyCid(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setReplyReplyId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setText(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSummary(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRich(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCommentUid(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCommentNick(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setFText(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setFSummary(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setFRich(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCText(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCSummary(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setCRich(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setRText(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setRSummary(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setRRich(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setPlaceid(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setPlace(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setLatitude(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setLongitude(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setAsComment(cursor.getShort(offset + 25) != 0);
        entity.setAsRepost(cursor.getShort(offset + 26) != 0);
        entity.setPic1(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setPic1Tmp(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setPic1Width(cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29));
        entity.setPic1Height(cursor.isNull(offset + 30) ? null : cursor.getInt(offset + 30));
        entity.setPic1Mimetype(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setPic1Key(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setPic1Url(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setPic2(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setPic2Tmp(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setPic2Width(cursor.isNull(offset + 36) ? null : cursor.getInt(offset + 36));
        entity.setPic2Height(cursor.isNull(offset + 37) ? null : cursor.getInt(offset + 37));
        entity.setPic2Mimetype(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setPic2Key(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setPic2Url(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setPic3(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setPic3Tmp(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setPic3Width(cursor.isNull(offset + 43) ? null : cursor.getInt(offset + 43));
        entity.setPic3Height(cursor.isNull(offset + 44) ? null : cursor.getInt(offset + 44));
        entity.setPic3Mimetype(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setPic3Key(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setPic3Url(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setPic4(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setPic4Tmp(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setPic4Width(cursor.isNull(offset + 50) ? null : cursor.getInt(offset + 50));
        entity.setPic4Height(cursor.isNull(offset + 51) ? null : cursor.getInt(offset + 51));
        entity.setPic4Mimetype(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setPic4Key(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setPic4Url(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setPic5(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setPic5Tmp(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setPic5Width(cursor.isNull(offset + 57) ? null : cursor.getInt(offset + 57));
        entity.setPic5Height(cursor.isNull(offset + 58) ? null : cursor.getInt(offset + 58));
        entity.setPic5Mimetype(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setPic5Key(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setPic5Url(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setPic6(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setPic6Tmp(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setPic6Width(cursor.isNull(offset + 64) ? null : cursor.getInt(offset + 64));
        entity.setPic6Height(cursor.isNull(offset + 65) ? null : cursor.getInt(offset + 65));
        entity.setPic6Mimetype(cursor.isNull(offset + 66) ? null : cursor.getString(offset + 66));
        entity.setPic6Key(cursor.isNull(offset + 67) ? null : cursor.getString(offset + 67));
        entity.setPic6Url(cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68));
        entity.setPic7(cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69));
        entity.setPic7Tmp(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
        entity.setPic7Width(cursor.isNull(offset + 71) ? null : cursor.getInt(offset + 71));
        entity.setPic7Height(cursor.isNull(offset + 72) ? null : cursor.getInt(offset + 72));
        entity.setPic7Mimetype(cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73));
        entity.setPic7Key(cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74));
        entity.setPic7Url(cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75));
        entity.setPic8(cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76));
        entity.setPic8Tmp(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
        entity.setPic8Width(cursor.isNull(offset + 78) ? null : cursor.getInt(offset + 78));
        entity.setPic8Height(cursor.isNull(offset + 79) ? null : cursor.getInt(offset + 79));
        entity.setPic8Mimetype(cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80));
        entity.setPic8Key(cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81));
        entity.setPic8Url(cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82));
        entity.setPic9(cursor.isNull(offset + 83) ? null : cursor.getString(offset + 83));
        entity.setPic9Tmp(cursor.isNull(offset + 84) ? null : cursor.getString(offset + 84));
        entity.setPic9Width(cursor.isNull(offset + 85) ? null : cursor.getInt(offset + 85));
        entity.setPic9Height(cursor.isNull(offset + 86) ? null : cursor.getInt(offset + 86));
        entity.setPic9Mimetype(cursor.isNull(offset + 87) ? null : cursor.getString(offset + 87));
        entity.setPic9Key(cursor.isNull(offset + 88) ? null : cursor.getString(offset + 88));
        entity.setPic9Url(cursor.isNull(offset + 89) ? null : cursor.getString(offset + 89));
        entity.setVideo(cursor.isNull(offset + 90) ? null : cursor.getString(offset + 90));
        entity.setVideoTmp(cursor.isNull(offset + 91) ? null : cursor.getString(offset + 91));
        entity.setVideoMimetype(cursor.isNull(offset + 92) ? null : cursor.getString(offset + 92));
        entity.setVideoDur(cursor.isNull(offset + 93) ? null : cursor.getLong(offset + 93));
        entity.setVideoKey(cursor.isNull(offset + 94) ? null : cursor.getString(offset + 94));
        entity.setVideoUrl(cursor.isNull(offset + 95) ? null : cursor.getString(offset + 95));
        entity.setVideoThumb(cursor.isNull(offset + 96) ? null : cursor.getString(offset + 96));
        entity.setVideoThumbTmp(cursor.isNull(offset + 97) ? null : cursor.getString(offset + 97));
        entity.setVideoThumbKey(cursor.isNull(offset + 98) ? null : cursor.getString(offset + 98));
        entity.setVideoThumbUrl(cursor.isNull(offset + 99) ? null : cursor.getString(offset + 99));
        entity.setVideoWidth(cursor.isNull(offset + 100) ? null : cursor.getInt(offset + 100));
        entity.setVideoHeight(cursor.isNull(offset + 101) ? null : cursor.getInt(offset + 101));
        entity.setForwardPid(cursor.isNull(offset + 102) ? null : cursor.getString(offset + 102));
        entity.setForwardDeleted(cursor.isNull(offset + 103) ? null : cursor.getShort(offset + 103) != 0);
        entity.setForwardUid(cursor.isNull(offset + 104) ? null : cursor.getString(offset + 104));
        entity.setForwardNick(cursor.isNull(offset + 105) ? null : cursor.getString(offset + 105));
        entity.setForwardHead(cursor.isNull(offset + 106) ? null : cursor.getString(offset + 106));
        entity.setForwardType(cursor.isNull(offset + 107) ? null : (byte) cursor.getShort(offset + 107));
        entity.setForwardLikeCount(cursor.isNull(offset + 108) ? null : cursor.getLong(offset + 108));
        entity.setForwardLikeValue(cursor.isNull(offset + 109) ? null : cursor.getInt(offset + 109));
        entity.setForwardCommentCount(cursor.isNull(offset + 110) ? null : cursor.getInt(offset + 110));
        entity.setForwardForwardCount(cursor.isNull(offset + 111) ? null : cursor.getInt(offset + 111));
        entity.setForwardText(cursor.isNull(offset + 112) ? null : cursor.getString(offset + 112));
        entity.setForwardSummary(cursor.isNull(offset + 113) ? null : cursor.getString(offset + 113));
        entity.setForwardRich(cursor.isNull(offset + 114) ? null : cursor.getString(offset + 114));
        entity.setForwardPic1(cursor.isNull(offset + 115) ? null : cursor.getString(offset + 115));
        entity.setForwardPic2(cursor.isNull(offset + 116) ? null : cursor.getString(offset + 116));
        entity.setForwardPic3(cursor.isNull(offset + 117) ? null : cursor.getString(offset + 117));
        entity.setForwardPic4(cursor.isNull(offset + 118) ? null : cursor.getString(offset + 118));
        entity.setForwardPic5(cursor.isNull(offset + 119) ? null : cursor.getString(offset + 119));
        entity.setForwardPic6(cursor.isNull(offset + 120) ? null : cursor.getString(offset + 120));
        entity.setForwardPic7(cursor.isNull(offset + 121) ? null : cursor.getString(offset + 121));
        entity.setForwardPic8(cursor.isNull(offset + 122) ? null : cursor.getString(offset + 122));
        entity.setForwardPic9(cursor.isNull(offset + 123) ? null : cursor.getString(offset + 123));
        entity.setForwardPic1Large(cursor.isNull(offset + 124) ? null : cursor.getString(offset + 124));
        entity.setForwardPic2Large(cursor.isNull(offset + 125) ? null : cursor.getString(offset + 125));
        entity.setForwardPic3Large(cursor.isNull(offset + 126) ? null : cursor.getString(offset + 126));
        entity.setForwardPic4Large(cursor.isNull(offset + 127) ? null : cursor.getString(offset + 127));
        entity.setForwardPic5Large(cursor.isNull(offset + 128) ? null : cursor.getString(offset + 128));
        entity.setForwardPic6Large(cursor.isNull(offset + 129) ? null : cursor.getString(offset + 129));
        entity.setForwardPic7Large(cursor.isNull(offset + 130) ? null : cursor.getString(offset + 130));
        entity.setForwardPic8Large(cursor.isNull(offset + 131) ? null : cursor.getString(offset + 131));
        entity.setForwardPic9Large(cursor.isNull(offset + 132) ? null : cursor.getString(offset + 132));
        entity.setForwardVideo(cursor.isNull(offset + 133) ? null : cursor.getString(offset + 133));
        entity.setForwardVideoThumb(cursor.isNull(offset + 134) ? null : cursor.getString(offset + 134));
        entity.setForwardLink(cursor.isNull(offset + 135) ? null : cursor.getString(offset + 135));
        entity.setForwardLinkTitle(cursor.isNull(offset + 136) ? null : cursor.getString(offset + 136));
        entity.setForwardLinkText(cursor.isNull(offset + 137) ? null : cursor.getString(offset + 137));
        entity.setForwardLinkImg(cursor.isNull(offset + 138) ? null : cursor.getString(offset + 138));
    }

    @Override
    protected final String updateKeyAfterInsert(Draft entity, long rowId) {
        return entity.getDraftId();
    }

    @Override
    public String getKey(Draft entity) {
        if (entity != null) {
            return entity.getDraftId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Draft entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
