package com.redefine.welike.base.dao.welike;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SEARCH_HISTORY".
 */
@Entity
public class SearchHistory {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String keyword;
    private long time;

    @Generated
    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    @Generated
    public SearchHistory(Long id, String keyword, long time) {
        this.id = id;
        this.keyword = keyword;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getKeyword() {
        return keyword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKeyword(@NotNull String keyword) {
        this.keyword = keyword;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

}
