package com.redefine.welike.base.dao.welike;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id
    @Unique
    private String uid;

    @NotNull
    private String nick;
    private byte sex;
    private long created;
    private String head;
    private Long atTime;
    private Integer vip;

    @Generated
    public User() {
    }

    public User(String uid) {
        this.uid = uid;
    }

    @Generated
    public User(String uid, String nick, byte sex, long created, String head, Long atTime, Integer vip) {
        this.uid = uid;
        this.nick = nick;
        this.sex = sex;
        this.created = created;
        this.head = head;
        this.atTime = atTime;
        this.vip = vip;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    @NotNull
    public String getNick() {
        return nick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNick(@NotNull String nick) {
        this.nick = nick;
    }

    public byte getSex() {
        return sex;
    }

    public void setSex(byte sex) {
        this.sex = sex;
    }

    public long getCreated() {
        return created;
    }

    public void setCreated(long created) {
        this.created = created;
    }

    public String getHead() {
        return head;
    }

    public void setHead(String head) {
        this.head = head;
    }

    public Long getAtTime() {
        return atTime;
    }

    public void setAtTime(Long atTime) {
        this.atTime = atTime;
    }

    public Integer getVip() {
        return vip;
    }

    public void setVip(Integer vip) {
        this.vip = vip;
    }

}
