package com.redefine.welike.common.api.bean;

import java.io.Serializable;
/**
 * generated by script.
 * Created on 2017-07-24 14:22:25.
*/
public class TestResult  implements Serializable{

    public Integer memberFlag;

}