package com.redefine.welike.base.dao.im;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.redefine.welike.base.dao.im.Message;
import com.redefine.welike.base.dao.im.Session;
import com.redefine.welike.base.dao.im.AccountSetting;

import com.redefine.welike.base.dao.im.MessageDao;
import com.redefine.welike.base.dao.im.SessionDao;
import com.redefine.welike.base.dao.im.AccountSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig accountSettingDaoConfig;

    private final MessageDao messageDao;
    private final SessionDao sessionDao;
    private final AccountSettingDao accountSettingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        accountSettingDaoConfig = daoConfigMap.get(AccountSettingDao.class).clone();
        accountSettingDaoConfig.initIdentityScope(type);

        messageDao = new MessageDao(messageDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        accountSettingDao = new AccountSettingDao(accountSettingDaoConfig, this);

        registerDao(Message.class, messageDao);
        registerDao(Session.class, sessionDao);
        registerDao(AccountSetting.class, accountSettingDao);
    }
    
    public void clear() {
        messageDaoConfig.clearIdentityScope();
        sessionDaoConfig.clearIdentityScope();
        accountSettingDaoConfig.clearIdentityScope();
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public AccountSettingDao getAccountSettingDao() {
        return accountSettingDao;
    }

}
