package com.redefine.welike.base.dao.im;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MESSAGE".
 */
@Entity
public class Message {

    @Id
    @Unique
    private String mid;

    @NotNull
    private String sid;

    @NotNull
    private String sessionNick;
    private String sessionHead;

    @NotNull
    private String senderUid;

    @NotNull
    private String senderNick;
    private String senderHead;
    private byte sessionType;
    private byte status;
    private long time;
    private byte type;
    private String text;
    private String thumb;
    private String pic;
    private String audio;
    private String video;
    private String fileName;

    @Generated
    public Message() {
    }

    public Message(String mid) {
        this.mid = mid;
    }

    @Generated
    public Message(String mid, String sid, String sessionNick, String sessionHead, String senderUid, String senderNick, String senderHead, byte sessionType, byte status, long time, byte type, String text, String thumb, String pic, String audio, String video, String fileName) {
        this.mid = mid;
        this.sid = sid;
        this.sessionNick = sessionNick;
        this.sessionHead = sessionHead;
        this.senderUid = senderUid;
        this.senderNick = senderNick;
        this.senderHead = senderHead;
        this.sessionType = sessionType;
        this.status = status;
        this.time = time;
        this.type = type;
        this.text = text;
        this.thumb = thumb;
        this.pic = pic;
        this.audio = audio;
        this.video = video;
        this.fileName = fileName;
    }

    public String getMid() {
        return mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }

    @NotNull
    public String getSid() {
        return sid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSid(@NotNull String sid) {
        this.sid = sid;
    }

    @NotNull
    public String getSessionNick() {
        return sessionNick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSessionNick(@NotNull String sessionNick) {
        this.sessionNick = sessionNick;
    }

    public String getSessionHead() {
        return sessionHead;
    }

    public void setSessionHead(String sessionHead) {
        this.sessionHead = sessionHead;
    }

    @NotNull
    public String getSenderUid() {
        return senderUid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSenderUid(@NotNull String senderUid) {
        this.senderUid = senderUid;
    }

    @NotNull
    public String getSenderNick() {
        return senderNick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSenderNick(@NotNull String senderNick) {
        this.senderNick = senderNick;
    }

    public String getSenderHead() {
        return senderHead;
    }

    public void setSenderHead(String senderHead) {
        this.senderHead = senderHead;
    }

    public byte getSessionType() {
        return sessionType;
    }

    public void setSessionType(byte sessionType) {
        this.sessionType = sessionType;
    }

    public byte getStatus() {
        return status;
    }

    public void setStatus(byte status) {
        this.status = status;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public byte getType() {
        return type;
    }

    public void setType(byte type) {
        this.type = type;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getAudio() {
        return audio;
    }

    public void setAudio(String audio) {
        this.audio = audio;
    }

    public String getVideo() {
        return video;
    }

    public void setVideo(String video) {
        this.video = video;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

}
