package com.redefine.welike.base.dao.im;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SESSION".
 */
@Entity
public class Session {

    @Id
    @Unique
    private String sid;

    @NotNull
    private String sessionNick;
    private String sessionHead;
    private String singleUid;
    private Byte msgType;
    private Boolean enableChat;
    private Boolean visableChat;
    private Boolean isGreet;
    private byte sessionType;
    private long time;
    private int unreadCount;
    private String content;

    @Generated
    public Session() {
    }

    public Session(String sid) {
        this.sid = sid;
    }

    @Generated
    public Session(String sid, String sessionNick, String sessionHead, String singleUid, Byte msgType, Boolean enableChat, Boolean visableChat, Boolean isGreet, byte sessionType, long time, int unreadCount, String content) {
        this.sid = sid;
        this.sessionNick = sessionNick;
        this.sessionHead = sessionHead;
        this.singleUid = singleUid;
        this.msgType = msgType;
        this.enableChat = enableChat;
        this.visableChat = visableChat;
        this.isGreet = isGreet;
        this.sessionType = sessionType;
        this.time = time;
        this.unreadCount = unreadCount;
        this.content = content;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    @NotNull
    public String getSessionNick() {
        return sessionNick;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSessionNick(@NotNull String sessionNick) {
        this.sessionNick = sessionNick;
    }

    public String getSessionHead() {
        return sessionHead;
    }

    public void setSessionHead(String sessionHead) {
        this.sessionHead = sessionHead;
    }

    public String getSingleUid() {
        return singleUid;
    }

    public void setSingleUid(String singleUid) {
        this.singleUid = singleUid;
    }

    public Byte getMsgType() {
        return msgType;
    }

    public void setMsgType(Byte msgType) {
        this.msgType = msgType;
    }

    public Boolean getEnableChat() {
        return enableChat;
    }

    public void setEnableChat(Boolean enableChat) {
        this.enableChat = enableChat;
    }

    public Boolean getVisableChat() {
        return visableChat;
    }

    public void setVisableChat(Boolean visableChat) {
        this.visableChat = visableChat;
    }

    public Boolean getIsGreet() {
        return isGreet;
    }

    public void setIsGreet(Boolean isGreet) {
        this.isGreet = isGreet;
    }

    public byte getSessionType() {
        return sessionType;
    }

    public void setSessionType(byte sessionType) {
        this.sessionType = sessionType;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public int getUnreadCount() {
        return unreadCount;
    }

    public void setUnreadCount(int unreadCount) {
        this.unreadCount = unreadCount;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
